export type SemanticDomain='trust'|'hazard'|'uncertainty'|'operation'|'approval'|'connectivity'|'privacy';
export type SemanticTone='verified'|'info'|'caution'|'critical'|'neutral'|'restricted';

export type SemanticStateDefinition={
 label:string;
 tone:SemanticTone;
 meaning:string;
};

type Registry=Record<SemanticDomain,Record<string,SemanticStateDefinition>>;

export const semanticStateRegistry:Registry={
 trust:{
  POVI_VERIFIED:{label:'PoVI Verified',tone:'verified',meaning:'A PoVI finality proof has been cryptographically verified against the trusted active validator set.'},
  DIR_RECORDED:{label:'DIR Recorded',tone:'info',meaning:'A DIR reference is recorded for this object. The reference alone does not establish independently verified PoVI finality or physical truth.'},
  RECORD_MATCHED:{label:'Record Matched',tone:'info',meaning:'The submitted identifier or fingerprint matches a record in the STRATUM verification index.'},
  FIELD_VERIFIED:{label:'Field Verified',tone:'verified',meaning:'A qualified field verification has been recorded.'},
  SURVEYED:{label:'Surveyed',tone:'info',meaning:'The state is supported by survey evidence.'},
  SCANNED:{label:'Scanned',tone:'info',meaning:'The state is supported by capture or scan evidence.'},
  OEM_VERIFIED:{label:'OEM Verified',tone:'verified',meaning:'The state is supported by OEM-origin evidence.'},
  SOURCE_VERIFIED:{label:'Source Verified',tone:'verified',meaning:'The state is supported by a verified source artifact.'},
  LIVE:{label:'Live',tone:'info',meaning:'The projection is currently connected to a live source.'},
  STALE:{label:'Stale',tone:'caution',meaning:'The projection is available but may not reflect current source state.'},
  UNCERTAIN:{label:'Uncertain',tone:'caution',meaning:'Available evidence does not justify a high-confidence conclusion.'},
  CONFLICTED:{label:'Conflicted',tone:'critical',meaning:'Trusted sources disagree and require resolution.'},
  INFERRED:{label:'Inferred',tone:'caution',meaning:'The state was reconstructed from indirect evidence.'},
  PREDICTED:{label:'Predicted',tone:'caution',meaning:'The state is a forecast and not an observed physical fact.'},
  AI_GENERATED:{label:'AI Generated',tone:'caution',meaning:'The state was generated by AI and has not become authority by generation alone.'},
  UNVERIFIED:{label:'Unverified',tone:'critical',meaning:'The state has not passed the required verification boundary.'},
 },
 hazard:{
  SAFE:{label:'Safe',tone:'verified',meaning:'No active hazard is known for the referenced scope.'},
  ADVISORY:{label:'Advisory',tone:'info',meaning:'Attention is recommended but the condition is not presently blocking.'},
  WARNING:{label:'Warning',tone:'caution',meaning:'A meaningful hazard or constraint requires action.'},
  CRITICAL:{label:'Critical',tone:'critical',meaning:'Immediate attention is required before proceeding.'},
 },
 uncertainty:{
  CERTAIN:{label:'Certain',tone:'verified',meaning:'The state is supported by sufficient direct evidence.'},
  ESTIMATED:{label:'Estimated',tone:'info',meaning:'The value is derived from an accepted estimate.'},
  UNCERTAIN:{label:'Uncertain',tone:'caution',meaning:'Confidence is insufficient for an authoritative conclusion.'},
  CONFLICTED:{label:'Conflicted',tone:'critical',meaning:'Evidence sources materially disagree.'},
 },
 operation:{
  ACTIVE:{label:'Active',tone:'verified',meaning:'The object or process is operating in its intended active state.'},
  INACTIVE:{label:'Inactive',tone:'neutral',meaning:'The object or process is not currently active.'},
  DEGRADED:{label:'Degraded',tone:'caution',meaning:'Operation continues with reduced capability or confidence.'},
  MAINTENANCE:{label:'Maintenance',tone:'info',meaning:'The object or process is intentionally in a maintenance state.'},
  OUTAGE:{label:'Outage',tone:'critical',meaning:'The object or process is unavailable for intended operation.'},
 },
 approval:{
  APPROVED:{label:'Approved',tone:'verified',meaning:'The required approval has been granted by the designated authority.'},
  PENDING:{label:'Pending approval',tone:'caution',meaning:'The approval decision is not yet final.'},
  REJECTED:{label:'Rejected',tone:'critical',meaning:'The required authority has rejected the item or transition.'},
  NOT_REQUIRED:{label:'Not required',tone:'neutral',meaning:'This scope does not require an approval decision.'},
 },
 connectivity:{
  ONLINE:{label:'Online',tone:'verified',meaning:'The connection is available and responsive.'},
  SYNCING:{label:'Syncing',tone:'info',meaning:'The connection is available while state synchronization is in progress.'},
  OFFLINE:{label:'Offline',tone:'critical',meaning:'The connection is unavailable.'},
  CONFLICT:{label:'Conflict',tone:'critical',meaning:'Connected peers or sources disagree about state.'},
 },
 privacy:{
  PUBLIC:{label:'Public',tone:'info',meaning:'The information is approved for public disclosure.'},
  INTERNAL:{label:'Internal',tone:'neutral',meaning:'The information is intended for authorized internal users.'},
  CLIENT:{label:'Client restricted',tone:'restricted',meaning:'Access is limited to the authorized client scope and approved STRATUM users.'},
  RESTRICTED:{label:'Restricted',tone:'restricted',meaning:'Access is limited to explicitly authorized roles or parties.'},
  PRIVATE:{label:'Private',tone:'restricted',meaning:'The information is private and should not be exposed beyond its approved scope.'},
 },
};

export function getSemanticState(domain:SemanticDomain,state:string):SemanticStateDefinition{
 const definition=semanticStateRegistry[domain][state];
 if(!definition)throw new Error(`Unknown semantic state ${domain}:${state}`);
 return definition;
}
