const captures=[
 {source:'360 Walkthrough',zone:'Electrical Room 2A',matched:18,exceptions:1,status:'Review'},
 {source:'Phone Capture',zone:'Utility Yard B',matched:9,exceptions:0,status:'Matched'},
 {source:'Drone / Exterior',zone:'Charging Yard C',matched:31,exceptions:2,status:'Review'}
];
export default function RealityPage(){return <>
  <div className="page-head"><div><div className="eyebrow">STRATUM Reality</div><h1 className="title">Compare design to what is actually there.</h1><p className="subtitle">Reality capture reconciles field imagery, 360° walkthroughs, LiDAR, point clouds and future drone/robotic capture against the approved project graph and digital twin.</p></div><div className="badge">DESIGN ↔ REALITY</div></div>
  <div className="grid kpis"><div className="card"><div className="label">Captured zones</div><div className="metric">3</div></div><div className="card"><div className="label">Matched assets</div><div className="metric">58</div></div><div className="card"><div className="label">Exceptions</div><div className="metric">3</div></div><div className="card"><div className="label">Reconciliation</div><div className="metric">95%</div></div></div>
  <div className="grid two"><div className="card"><div className="eyebrow">Reality reconciliation queue</div><table className="table"><thead><tr><th>Capture</th><th>Zone</th><th>Matched</th><th>Exceptions</th><th>Status</th></tr></thead><tbody>{captures.map(c=><tr key={c.source}><td>{c.source}</td><td>{c.zone}</td><td>{c.matched}</td><td>{c.exceptions}</td><td><span className={c.status==='Matched'?'proof':'pending'}>{c.status}</span></td></tr>)}</tbody></table></div>
  <div className="card"><div className="eyebrow">Exception intelligence</div><h2>Field vs design</h2><div className="timeline"><div className="event"><i className="event-icon">!</i><div><strong>MSB-01 position variance</strong><small>Observed location differs from design coordinate. Requires engineer validation before as-built update.</small></div></div><div className="event"><i className="event-icon">+</i><div><strong>Unexpected disconnect detected</strong><small>Possible new asset not present in approved design. Create candidate asset or reject as false positive.</small></div></div><div className="event"><i className="event-icon">?</i><div><strong>EVSE-C09 obscured</strong><small>Asset expected by design but not confidently visible in latest capture.</small></div></div></div></div></div>
  <div className="card" style={{marginTop:16}}><div className="eyebrow">Closed loop</div><div className="provenance-map"><div className="prov-step active"><i>01</i><b>Capture</b><span>Phone · 360 · LiDAR · drone</span></div><em>→</em><div className="prov-step active"><i>02</i><b>Recognize</b><span>Geometry · equipment · tags</span></div><em>→</em><div className="prov-step active"><i>03</i><b>Compare</b><span>Design vs installed</span></div><em>→</em><div className="prov-step active"><i>04</i><b>Validate</b><span>Human review + exceptions</span></div><em>→</em><div className="prov-step active"><i>05</i><b>As-Built Record</b><span>Verified update → DIRS</span></div></div></div>
</>}
