import Link from 'next/link';
import {assets} from '@/lib/data';
import {designedStates,observations,realityDiscrepancies,realitySummary,verifiedStates,REALITY_VALIDATION_AUTHORITY} from '@/lib/reality-validation';

const display=(value:string|number|boolean|null)=>value===null?'Not observed':String(value);

export default function RealityPage(){
 const summary=realitySummary();
 return <>
  <div className="page-head"><div><div className="eyebrow">STRATUM Reality Validation · Reference Comparison</div><h1 className="title">Designed. Observed. Verified—kept deliberately separate.</h1><p className="subtitle">Reference field observations are compared against approved engineering intent without silently changing Verified spatial or electrical state. Variances remain evidence-bound review candidates until tenant-backed capture, authorized review and governed persistence are completed.</p></div><div className="badge">REFERENCE DATA · HITL · READ-ONLY</div></div>
  <div className="card" style={{marginBottom:16}}><div className="eyebrow">Truth boundary</div><strong>Observed never overwrites Verified.</strong><p className="muted">This workspace is currently {REALITY_VALIDATION_AUTHORITY}. It proves deterministic comparison and review semantics, not live physical truth, PoVI finality, or an as-built update.</p></div>
  <div className="grid kpis"><div className="card"><div className="label">Reference captured assets</div><div className="metric">{summary.capturedAssets}</div></div><div className="card"><div className="label">Exact matches</div><div className="metric">{summary.matchedAssets}/{summary.comparedAssets}</div></div><div className="card"><div className="label">Discrepancies</div><div className="metric">{summary.discrepancies}</div><div className="muted">{summary.critical} critical</div></div><div className="card"><div className="label">Reference reconciliation</div><div className="metric">{summary.reconciliation}%</div></div></div>
  <div className="card table-card" style={{marginTop:16}}><div className="section-head"><div><div className="eyebrow">Deterministic comparison queue</div><h2>Engineering variances requiring disposition</h2></div><span className="pending">{summary.discrepancies} REVIEW REQUIRED</span></div><table className="table"><thead><tr><th>Asset / field</th><th>Designed</th><th>Observed</th><th>Verified</th><th>Confidence</th><th>Impact</th></tr></thead><tbody>{realityDiscrepancies.map(item=>{const asset=assets.find(candidate=>candidate.id===item.assetId);return <tr key={item.id}><td><strong>{asset?.name}</strong><div className="muted">{item.field} · {item.severity}</div></td><td>{display(item.designed)}</td><td><span className="pending">{display(item.observed)}</span></td><td><span className="proof">{display(item.verified)}</span></td><td>{Math.round(item.confidence*100)}%</td><td>{item.affectedAssets.length?`${item.affectedAssets.length} downstream asset${item.affectedAssets.length===1?'':'s'}`:'No downstream dependency'}</td></tr>})}{!realityDiscrepancies.length&&<tr><td colSpan={6}><span className="proof">All compared attributes match.</span></td></tr>}</tbody></table></div>
  <div className="grid two" style={{marginTop:16}}><div className="card"><div className="eyebrow">Three-state asset truth</div><h2>Source isolation is enforced</h2>{observations.map(observation=>{const asset=assets.find(candidate=>candidate.id===observation.assetId)!;const designed=designedStates[asset.id],verified=verifiedStates[asset.id],needsReview=realityDiscrepancies.some(discrepancy=>discrepancy.assetId===asset.id);return <div className="file-row" key={observation.id}><div className="file-icon">{Math.round(observation.confidence*100)}</div><div><strong>{asset.name}</strong><small>Designed: {designed.manufacturer} · Observed: {observation.state.manufacturer} · Verified: {verified.manufacturer}</small><small>{observation.source.replaceAll('_',' ')} · {observation.modelVersion} · evidence {observation.evidenceHash.slice(0,18)}…</small></div><span className={needsReview?'pending':'proof'}>{needsReview?'Review':'Matched'}</span></div>})}</div><div className="card"><div className="eyebrow">Implementation status</div><h2>What is proven vs still pending</h2><div className="custody"><div><i/>Implemented<span>Designed / Observed / Verified state isolation</span></div><div><i/>Implemented<span>OEM alias normalization and deterministic field comparison</span></div><div><i/>Implemented<span>Electrical downstream impact lookup</span></div><div><i/>Partial<span>Reference observations only; tenant-backed capture and persistence remain pending</span></div><div><i/>Planned<span>OCR, computer vision, LiDAR and external capture connectors</span></div></div><div className="button-row"><Link className="action" href="/spatial">Open spatial model</Link><Link className="ghost" href="/evidence">Review evidence</Link></div></div></div>
  <div className="card" style={{marginTop:16}}><div className="eyebrow">Governed reality lifecycle</div><div className="provenance-map"><div className="prov-step active"><i>01</i><b>Design</b><span>Approved intent · OEM data</span></div><em>→</em><div className="prov-step active"><i>02</i><b>Observe</b><span>Photo · scan · test · IoT</span></div><em>→</em><div className="prov-step active"><i>03</i><b>Compare</b><span>Deterministic variance rules</span></div><em>→</em><div className="prov-step active"><i>04</i><b>Challenge</b><span>Impact · confidence · HITL</span></div><em>→</em><div className="prov-step"><i>05</i><b>Verify</b><span>Authorized review before state change</span></div><em>→</em><div className="prov-step"><i>06</i><b>DIR</b><span>Approved provenance only</span></div></div></div>
 </>;
}
