import Link from 'next/link';
import {assets,events,projects} from '@/lib/data';
import AssetPassport from '@/components/AssetPassport';
import TrustBadge from '@/components/TrustBadge';

export default function Home(){
 const verified=assets.filter(a=>a.block).length;
 return <>
  <div className="topline"><div><div className="eyebrow">STRATUM Spatial Verified · Universal Command Center</div><h1 className="title">Know what exists. Know what happened. Know why it is trusted.</h1><div className="subtitle">STRATUM Spatial Verified is the spatial operating and trust model for physical infrastructure. It keeps source, live state, engineering approval, evidence and PoVI finality distinct while connecting them through one attributable history.</div></div><div className="badge">DIRs · stratum-devnet-1</div></div>

  <section className="hero"><div className="card hero-copy"><div className="eyebrow">Spatial → Evidence → Approval → Finality</div><h2>One durable infrastructure identity across design, installation, commissioning and operations.</h2><p className="muted">The current application is being converged to Redbook 1.0. Legacy Twin internals may remain temporarily for compatibility, but all user-facing product language and workflows now move toward STRATUM Spatial Verified.</p><div className="button-row"><Link className="action" href="/spatial">Open Spatial workspace</Link><Link className="ghost" href="/dir">Open DIR Explorer</Link></div><div className="trust-row"><TrustBadge state="LIVE"/><TrustBadge state={verified?'POVI_VERIFIED':'UNVERIFIED'}/><TrustBadge state="SOURCE_VERIFIED"/></div></div><div className="card layer-visual"><div className="layer l1"><b>Source</b><span>Documents · capture · OEM · telemetry</span></div><div className="layer l2"><b>Spatial</b><span>Site · building · room · system · asset</span></div><div className="layer l3"><b>Execution</b><span>Field work · QA/QC · commissioning</span></div><div className="layer l4"><b>Trust</b><span>Evidence · HITL · approvals · provenance</span></div><div className="layer l5"><b>PoVI</b><span>NDIR · MDIR · DIR · finality</span></div></div></section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">Redbook implementation order</div><h2>Build by convergence, not replacement</h2></div></div><div className="redbook-priority-grid"><div className="card redbook-priority"><span className="implementation-chip partial">P0 · PARTIAL</span><h3>Canonical Trust Foundation</h3><p className="muted">Canonical schemas and terminology, PoVI target, NDIR/MDIR/DIR hierarchy, validator registry and portable validator path.</p></div><div className="card redbook-priority"><span className="implementation-chip foundation">P1 · IN PROGRESS</span><h3>Platform Convergence</h3><p className="muted">STRATUM Spatial Verified, Data Room, AI Costing and JARVIS converge around shared canonical objects and trust semantics.</p></div><div className="card redbook-priority"><span className="implementation-chip planned">P2 · PLANNED</span><h3>Field / Engineering / OT</h3><p className="muted">OPC UA, edge runtime, Spatial reconstruction, power services, QA, safety, commissioning and operations.</p></div><div className="card redbook-priority"><span className="implementation-chip planned">P3 · PLANNED</span><h3>Ecosystem / Scale</h3><p className="muted">External connectors, Studio/SIR/WASM, enterprise certification and sovereign-scale validator deployments.</p></div></div></section>

  <section className="grid kpis" style={{marginTop:16}}><div className="card"><div className="label">Tracked Assets</div><div className="metric">{projects.reduce((n,p)=>n+p.assets,0).toLocaleString()}</div><div className="muted">Current application dataset</div></div><div className="card"><div className="label">PoVI-linked Passports</div><div className="metric">{verified}/{assets.length}</div><div className="muted">Current demo/passport cohort</div></div><div className="card"><div className="label">Visible Lifecycle Events</div><div className="metric">{events.length}</div><div className="muted">Current command-center stream</div></div><div className="card"><div className="label">Trust Rule</div><div className="metric" style={{fontSize:18}}>No silent promotion</div><div className="muted">Live, approved, inferred and finalized remain distinct</div></div></section>

  <section className="grid two"><div><div className="section-head"><div><div className="eyebrow">Universal Asset View</div><h2>Infrastructure provenance at a glance</h2></div></div><AssetPassport asset={assets[0]}/></div><div className="card"><div className="section-head"><div><div className="eyebrow">Activity</div><h3>Evidence and trust stream</h3></div></div><div className="timeline">{events.map(e=><div className="event" key={e.meta}><i className={`event-icon ${e.kind}`}>✓</i><div><strong>{e.title}</strong><small>{e.meta}</small></div></div>)}</div></div></section>
 </>;
}
