'use client';

import {useEffect,useState} from 'react';

type Invite={email:string;role:string;createdAt:string};
const roles=['ORG_ADMIN','PROJECT_MANAGER','TECHNICIAN','INSPECTOR','CLIENT','VIEWER'];

export default function AdminInvite(){const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [role,setRole]=useState('VIEWER');const [items,setItems]=useState<Invite[]>([]);const [message,setMessage]=useState('');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('stratum-admin-invites')||'[]'));}catch{}},[]);
 function save(next:Invite[]){setItems(next);localStorage.setItem('stratum-admin-invites',JSON.stringify(next));}
 async function create(){const clean=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(clean)){setMessage('Enter a valid email address.');return;}const invite={email:clean,role,createdAt:new Date().toISOString()};save([invite,...items.filter(x=>x.email!==clean)]);const text=`STRATUM Verified invitation\nEmail: ${clean}\nRole: ${role}\nWorkspace: ${location.origin}`;try{await navigator.clipboard.writeText(text);setMessage('Invite prepared and copied. Open your mail client to send it.');}catch{setMessage('Invite prepared. Use the mail button to send it.');}}
 function remove(email:string){save(items.filter(x=>x.email!==email));}
 return <div><button type="button" className="action" onClick={()=>setOpen(v=>!v)}>{open?'Close invite':'Invite user'}</button>{open&&<div className="card" style={{marginTop:12}}><div className="eyebrow">User invitation</div><div style={{display:'grid',gap:8,marginTop:10}}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="user@company.com"/><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><div className="button-row"><button type="button" onClick={create}>Prepare invite</button><a className="ghost" href={`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent('STRATUM Verified invitation')}&body=${encodeURIComponent(`You have been invited to STRATUM Verified as ${role}. Open ${typeof location!=='undefined'?location.origin:''}`)}`}>Open mail</a></div>{message&&<div className="notice"><strong>STATUS</strong><span>{message}</span></div>}<small className="muted">This UI prepares and tracks invitations locally. Tenant-side account provisioning remains protected by the authentication/user-management backend and should not be simulated.</small></div>{items.length>0&&<div style={{marginTop:14}}>{items.map(i=><div key={i.email} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'8px 0',borderTop:'1px solid #1d3446'}}><div><strong>{i.email}</strong><div className="muted">{i.role.replaceAll('_',' ')}</div></div><button type="button" onClick={()=>remove(i.email)}>Remove</button></div>)}</div>}</div>}</div>}
