'use client';

import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';

type Layer='L0'|'L1'|'L2'|'L3'|'L4';
type Entity={id:string;source:string;layer:Layer;kind:string;name:string;x:number;y:number;x2?:number;y2?:number;confidence:number;meta?:Record<string,unknown>};
type Graph={version:string;createdAt:string;sources:{name:string;ext:string;sha256:string;discipline:string}[];entities:Entity[];stats:Record<Layer,number>};
const layerNames:Record<Layer,string>={L0:'Source',L1:'Architectural',L2:'Electrical Physical',L3:'Electrical Logical',L4:'STRATUM Assets'};
const colors:Record<Layer,number>={L0:0x1d4964,L1:0x71899b,L2:0xd28a3e,L3:0x58b7ff,L4:0x39db8a};

export default function CompiledGraphViewer(){
 const mount=useRef<HTMLDivElement|null>(null);const [graph,setGraph]=useState<Graph|null>(null);const [active,setActive]=useState<Layer[]>(['L0','L1','L2','L3','L4']);const [selected,setSelected]=useState<Entity|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('stratum_compiled_graph');if(raw)setGraph(JSON.parse(raw))}catch{}},[]);
 const counts=useMemo(()=>graph?(['L0','L1','L2','L3','L4'] as Layer[]).reduce((a,l)=>({...a,[l]:l==='L0'?graph.sources.length:graph.entities.filter(e=>e.layer===l).length}),{} as Record<Layer,number>):null,[graph]);
 useEffect(()=>{if(!graph||!mount.current)return;let disposed=false;let cleanup=()=>{};(async()=>{const THREE=await import('three');const {OrbitControls}=await import('three/examples/jsm/controls/OrbitControls.js');if(disposed||!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x051019);scene.fog=new THREE.FogExp2(0x051019,.018);const camera=new THREE.PerspectiveCamera(43,host.clientWidth/Math.max(host.clientHeight,1),.1,500);camera.position.set(16,15,18);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;host.replaceChildren(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xcbeeff,0x061018,2.3));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(8,14,10);scene.add(key);
  const groups:Record<Layer,any>={L0:new THREE.Group(),L1:new THREE.Group(),L2:new THREE.Group(),L3:new THREE.Group(),L4:new THREE.Group()};(Object.keys(groups) as Layer[]).forEach(l=>{groups[l].visible=active.includes(l);scene.add(groups[l])});const clickable:any[]=[];
  if(active.includes('L0')){const source=new THREE.Mesh(new THREE.PlaneGeometry(22,15),new THREE.MeshStandardMaterial({color:colors.L0,transparent:true,opacity:.18,side:THREE.DoubleSide}));source.rotation.x=-Math.PI/2;source.position.y=-.06;groups.L0.add(source)}
  const material=(l:Layer)=>new THREE.MeshStandardMaterial({color:colors[l],emissive:colors[l],emissiveIntensity:.08,metalness:.2,roughness:.55});
  for(const e of graph.entities){const l=e.layer;if(!groups[l])continue;if(e.kind==='line'&&Number.isFinite(e.x2)&&Number.isFinite(e.y2)){const pts=[new THREE.Vector3(e.x,.04,e.y),new THREE.Vector3(e.x2!,.04,e.y2!)];groups[l].add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:colors[l]})));continue}const isPhysical=l==='L2';const geo=isPhysical?new THREE.BoxGeometry(.48,.65,.48):new THREE.SphereGeometry(.16,12,8);const obj=new THREE.Mesh(geo,material(l));obj.position.set(e.x,isPhysical?.34:.16,e.y);obj.userData.entity=e;groups[l].add(obj);clickable.push(obj);if(isPhysical){const ring=new THREE.Mesh(new THREE.TorusGeometry(.36,.025,8,32),new THREE.MeshBasicMaterial({color:colors.L4}));ring.rotation.x=Math.PI/2;ring.position.set(e.x,.02,e.y);groups.L4.add(ring)}}
  scene.add(new THREE.GridHelper(30,30,0x24495e,0x102936));const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const click=(ev:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((ev.clientX-rect.left)/rect.width)*2-1;pointer.y=-((ev.clientY-rect.top)/rect.height)*2+1;ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(clickable,true)[0];if(hit?.object?.userData?.entity)setSelected(hit.object.userData.entity)};renderer.domElement.addEventListener('pointerup',click);const resize=()=>{if(!host.clientWidth||!host.clientHeight)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};const ro=new ResizeObserver(resize);ro.observe(host);let f=0;const animate=()=>{controls.update();renderer.render(scene,camera);f=requestAnimationFrame(animate)};animate();cleanup=()=>{cancelAnimationFrame(f);ro.disconnect();renderer.domElement.removeEventListener('pointerup',click);controls.dispose();renderer.dispose();host.replaceChildren()}})();return()=>{disposed=true;cleanup()}},[graph,active]);
 if(!graph)return null;
 return <section style={{border:'1px solid #1b3a50',borderRadius:20,overflow:'hidden',background:'#07111b',marginBottom:18}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',padding:'14px 16px',borderBottom:'1px solid #17334a',flexWrap:'wrap'}}><div><div className="eyebrow">COMPILED DRAWING TWIN · REAL SOURCE GRAPH</div><strong>{graph.sources.map(s=>s.name).join(' · ')}</strong><div className="muted">Compiled {new Date(graph.createdAt).toLocaleString()} · parser v{graph.version}</div></div><Link className="ghost" href="/compiler">Recompile sources</Link></div>
  <div style={{display:'flex',gap:6,padding:'10px 12px',overflowX:'auto',borderBottom:'1px solid #17334a'}}>{(['L0','L1','L2','L3','L4'] as Layer[]).map(l=><button key={l} onClick={()=>setActive(v=>v.includes(l)?v.filter(x=>x!==l):[...v,l])} style={{flex:'0 0 auto',border:'1px solid #28465f',background:active.includes(l)?'#0b2d20':'#08131d',color:active.includes(l)?'#7ce5ae':'#7590a5',borderRadius:10,padding:'8px 10px',cursor:'pointer'}}><b>{l}</b> {layerNames[l]} · {counts?.[l]||0}</button>)}</div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(240px,320px)'}} className="compiled-twin-grid"><div ref={mount} style={{height:'min(66vh,650px)',minHeight:430}}/><aside style={{padding:16,borderLeft:'1px solid #17334a',overflow:'auto'}}><div className="eyebrow">SOURCE-GROUNDED OBJECT</div>{selected?<><h2 style={{marginBottom:6}}>{selected.name}</h2><div className="subtitle">{selected.kind} · {selected.layer} {layerNames[selected.layer]}</div><div className="passport-facts" style={{marginTop:14}}><div><span>Source</span><strong>{selected.source}</strong></div><div><span>Confidence</span><strong>{Math.round(selected.confidence*100)}%</strong></div><div><span>X</span><strong>{selected.x.toFixed(2)}</strong></div><div><span>Y</span><strong>{selected.y.toFixed(2)}</strong></div></div><p className="subtitle" style={{marginTop:14}}>This object came from the uploaded engineering source. It is not DIR-verified until validated, bound to an asset identity and approved.</p></>:<p className="subtitle">Click a parsed equipment or tag marker to inspect its source-derived identity and coordinates.</p>}<div className="notice" style={{marginTop:16}}><strong>DIR BOUNDARY</strong><span>Compilation does not automatically make engineering inference immutable. Validation and approval occur before Digital Immutable Records are finalized.</span></div></aside></div>
  <style jsx>{`@media(max-width:820px){.compiled-twin-grid{grid-template-columns:1fr!important}.compiled-twin-grid aside{border-left:0!important;border-top:1px solid #17334a}}`}</style>
 </section>
}
