'use client';

import {ChangeEvent,useState} from 'react';

type Selected={file:File;sha256:string};

export default function EvidenceUpload(){
 const [assetId,setAssetId]=useState('');const [eventId,setEventId]=useState('');const [kind,setKind]=useState('Inspection');const [visibility,setVisibility]=useState('PRIVATE');const [selected,setSelected]=useState<Selected|null>(null);const [message,setMessage]=useState('Select a file and provide the live asset + lifecycle event IDs.');const [busy,setBusy]=useState(false);
 async function choose(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const d=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());const sha256=Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');setSelected({file,sha256});setMessage(`Fingerprint ready: ${sha256.slice(0,18)}…`);}finally{setBusy(false)}}
 async function upload(){if(!selected||!assetId.trim()||!eventId.trim()){setMessage('Asset ID, lifecycle event ID and file are required.');return;}setBusy(true);setMessage('Uploading evidence…');try{const fd=new FormData();fd.set('file',selected.file);fd.set('assetId',assetId.trim());fd.set('lifecycleEventId',eventId.trim());fd.set('kind',kind);fd.set('visibility',visibility);fd.set('sha256',selected.sha256);const r=await fetch('/api/evidence/upload',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');setMessage(`Evidence stored and fingerprint verified: ${String(j.sha256||selected.sha256).slice(0,22)}…`);setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false)}}
 return <div className="card" id="upload-evidence"><div className="eyebrow">Upload evidence</div><h3>Attach a private file to a lifecycle record</h3><p className="muted">The browser computes SHA-256 first; the server recomputes it and rejects mismatches before storing the file.</p><div style={{display:'grid',gap:10}}><input value={assetId} onChange={e=>setAssetId(e.target.value)} placeholder="Live asset UUID"/><input value={eventId} onChange={e=>setEventId(e.target.value)} placeholder="Lifecycle event UUID"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><input value={kind} onChange={e=>setKind(e.target.value)} placeholder="Evidence type"/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="PRIVATE">Private</option><option value="CLIENT">Client</option><option value="PUBLIC">Public metadata</option></select></div><input type="file" onChange={choose}/>{selected&&<div className="notice"><strong>{selected.file.name}</strong><span style={{wordBreak:'break-all'}}>SHA-256 {selected.sha256}</span></div>}<button type="button" className="action" disabled={busy||!selected} onClick={upload}>{busy?'Working…':'Upload & verify evidence'}</button><div className="notice"><strong>STATUS</strong><span>{message}</span></div></div></div>;
}
