'use client';

import {ChangeEvent,useEffect,useMemo,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';

type ResolvedAsset={id:string;asset_code:string;asset_type:string;name:string;serial_number:string|null;location_label:string|null;status:string;project_id:string;project_code:string;project_name:string;site_name:string;system_name:string|null};
type EvidenceMeta={name:string;sha256:string;type:string;size:number};
type Draft={locationConfirmed:boolean;checklist:boolean;measurements:string;notes:string;technician:string;supervisor:string;evidence:EvidenceMeta[];submitted:boolean;recordId?:string;canonicalHash?:string};

const empty:Draft={locationConfirmed:false,checklist:false,measurements:'',notes:'',technician:'',supervisor:'',evidence:[],submitted:false};
const uuid=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);

export default function InspectionSession(){
 const q=useSearchParams().get('q')||'';const router=useRouter();
 const [asset,setAsset]=useState<ResolvedAsset|null>(null);const [source,setSource]=useState('');
 const [draft,setDraft]=useState<Draft>(empty);const [message,setMessage]=useState(q?'Resolving asset…':'No asset identifier supplied.');const [busy,setBusy]=useState(false);
 const filesRef=useRef<Map<string,File>>(new Map());
 const key=asset?`stratum-inspection:${asset.id}`:'';
 useEffect(()=>{if(!q)return;(async()=>{try{const r=await fetch(`/api/assets/resolve?q=${encodeURIComponent(q)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Asset lookup failed');setAsset(j.asset);setSource(j.source);setMessage('Asset identified. Complete the inspection steps below.');}catch(e){setMessage(e instanceof Error?e.message:'Asset lookup failed');}})()},[q]);
 useEffect(()=>{if(!key)return;try{const raw=localStorage.getItem(key);if(raw){const saved=JSON.parse(raw);setDraft({...empty,...saved,evidence:saved.evidence||saved.photos||[],submitted:Boolean(saved.submitted)});}}catch{}},[key]);
 useEffect(()=>{if(!key)return;localStorage.setItem(key,JSON.stringify(draft));},[key,draft]);
 const complete=useMemo(()=>!!asset&&draft.locationConfirmed&&draft.checklist&&!!draft.measurements.trim()&&!!draft.technician.trim()&&!!draft.supervisor.trim()&&draft.evidence.length>0,[asset,draft]);
 const submitDisabled=!complete||busy||draft.submitted;
 async function addEvidence(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);if(!files.length)return;setBusy(true);try{const out:EvidenceMeta[]=[];for(const f of files){const d=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());const sha256=Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');filesRef.current.set(sha256,f);out.push({name:f.name,sha256,type:f.type||'application/octet-stream',size:f.size});}setDraft(v=>({...v,evidence:[...v.evidence.filter(x=>!out.some(o=>o.sha256===x.sha256)),...out]}));setMessage('Evidence fingerprinted. Keep this page open until submission so the files can be uploaded.');}finally{setBusy(false);e.target.value='';}}
 function removeEvidence(sha256:string){filesRef.current.delete(sha256);setDraft(v=>({...v,evidence:v.evidence.filter(x=>x.sha256!==sha256)}));}
 async function uploadEvidence(recordId:string){if(!asset)return 0;let uploaded=0;for(const meta of draft.evidence){const file=filesRef.current.get(meta.sha256);if(!file)continue;const fd=new FormData();fd.set('file',file);fd.set('lifecycleEventId',recordId);fd.set('assetId',asset.id);fd.set('kind','Inspection');fd.set('visibility','PRIVATE');fd.set('sha256',meta.sha256);const r=await fetch('/api/evidence/upload',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||`Evidence upload failed for ${meta.name}`);uploaded++;}return uploaded;}
 async function submit(){if(!asset||!complete)return;setBusy(true);setMessage('Creating inspection record…');try{
   if(source==='live'&&uuid(asset.id)&&uuid(asset.project_id)){
    const r=await fetch('/api/lifecycle',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:asset.project_id,assetId:asset.id,eventType:'INSPECT',payload:{locationConfirmed:draft.locationConfirmed,checklistPassed:draft.checklist,measurements:draft.measurements,notes:draft.notes,technician:draft.technician,supervisor:draft.supervisor,evidence:draft.evidence}})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Inspection submission failed');
    const recordId=String(j.id||j.record_id||'');let uploaded=0;if(recordId)uploaded=await uploadEvidence(recordId);
    const missing=draft.evidence.length-uploaded;setMessage(`Inspection submitted${uploaded?` with ${uploaded} evidence file${uploaded===1?'':'s'} stored`:''}${missing?`. ${missing} saved fingerprint${missing===1?' has':'s have'} no active file handle and must be reselected before upload`:''}. DIR candidate hash ${j.canonicalHash?.slice(0,18)||''}…`);setDraft(v=>({...v,submitted:true,recordId,canonicalHash:j.canonicalHash}));
   }else{setMessage('Reference asset inspection completed locally. Live submission will be available when this asset is registered in the production tenant.');setDraft(v=>({...v,submitted:true}));}
  }catch(e){setMessage(e instanceof Error?e.message:'Inspection submission failed');}finally{setBusy(false)}}
 if(!q)return <div className="card"><h2>No asset selected</h2><p className="muted">Scan an asset first.</p><button type="button" onClick={()=>router.push('/workflows')}>Open field scanner</button></div>;
 return <div className="grid two" style={{alignItems:'start'}}>
  <div className="card"><div className="eyebrow">Field inspection session</div><h2>{asset?.name||'Resolving asset'}</h2><p className="subtitle">{asset?`${asset.asset_code} · ${asset.site_name} · ${asset.location_label||'Location pending'}`:message}</p>{asset&&<div className="timeline">
   <label className="event"><input type="checkbox" checked={draft.locationConfirmed} onChange={e=>setDraft(v=>({...v,locationConfirmed:e.target.checked}))}/><div><strong>Confirm site & location</strong><small>{asset.site_name} · {asset.location_label||'Location pending'}</small></div></label>
   <label className="event"><input type="checkbox" checked={draft.checklist} onChange={e=>setDraft(v=>({...v,checklist:e.target.checked}))}/><div><strong>Inspection checklist passed</strong><small>Visual condition, labeling, clearances, mounting and workmanship reviewed.</small></div></label>
   <div className="event"><div style={{width:'100%'}}><strong>Measurements</strong><textarea value={draft.measurements} onChange={e=>setDraft(v=>({...v,measurements:e.target.value}))} placeholder="Voltage, current, torque, IR values, test results…" style={{width:'100%',minHeight:90,marginTop:8}}/></div></div>
   <div className="event"><div style={{width:'100%'}}><strong>Installation / inspection evidence</strong><input type="file" multiple accept="image/*,.pdf" onChange={addEvidence}/><small>{draft.evidence.length?`${draft.evidence.length} evidence file(s) fingerprinted with SHA-256`:'At least one evidence file is required.'}</small>{draft.evidence.map(x=><div key={x.sha256} style={{display:'flex',gap:8,justifyContent:'space-between',alignItems:'center',marginTop:7,fontSize:12}}><span style={{overflow:'hidden',textOverflow:'ellipsis'}}>{x.name}</span><button type="button" onClick={()=>removeEvidence(x.sha256)}>Remove</button></div>)}</div></div>
   <div className="event"><div style={{width:'100%'}}><strong>Technician signature / name</strong><input value={draft.technician} onChange={e=>setDraft(v=>({...v,technician:e.target.value}))} placeholder="Technician name" style={{width:'100%',marginTop:8}}/></div></div>
   <div className="event"><div style={{width:'100%'}}><strong>Supervisor / inspector</strong><input value={draft.supervisor} onChange={e=>setDraft(v=>({...v,supervisor:e.target.value}))} placeholder="Supervisor / inspector name" style={{width:'100%',marginTop:8}}/></div></div>
   <div className="event"><div style={{width:'100%'}}><strong>Notes</strong><textarea value={draft.notes} onChange={e=>setDraft(v=>({...v,notes:e.target.value}))} placeholder="Exceptions, observations, corrective actions…" style={{width:'100%',minHeight:70,marginTop:8}}/></div></div>
  </div>}</div>
  <div className="card"><div className="eyebrow">Workflow status</div><h2>{draft.submitted?'Inspection complete':'Ready when all required steps pass'}</h2><div className="workflow-steps">{[['Asset identified',!!asset],['Location confirmed',draft.locationConfirmed],['Checklist complete',draft.checklist],['Measurements recorded',!!draft.measurements.trim()],['Evidence attached',draft.evidence.length>0],['Technician identified',!!draft.technician.trim()],['Supervisor recorded',!!draft.supervisor.trim()],['DIR candidate ready',complete]].map(([t,ok],i)=><div className={`workflow-step ${ok?'done':''}`} key={String(t)}><i>{ok?'✓':i+1}</i><div><strong>{String(t)}</strong><span>{ok?'Complete':'Required'}</span></div></div>)}</div><button type="button" onClick={submit} disabled={submitDisabled} style={{width:'100%',marginTop:16,opacity:submitDisabled?0.55:1}}>{busy?'Submitting…':draft.submitted?'Submitted':'Submit inspection & create DIR candidate'}</button><div className="notice" style={{marginTop:12}}><strong>STATUS</strong><span>{message}</span></div>{asset&&<div className="button-row" style={{marginTop:12}}><button type="button" onClick={()=>router.push(`/assets/${encodeURIComponent(asset.id)}`)}>Open passport</button><button type="button" onClick={()=>router.push('/workflows')}>Scan another</button></div>}</div>
 </div>;
}
