'use client';

import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {ELECTRICAL_CATEGORIES,ELECTRICAL_COMPONENTS} from '@/lib/electrical-component-library';
import {DEFAULT_ELECTRICAL_MODEL_REGISTRY,ELECTRICAL_MODEL_REGISTRY_STORAGE_KEY,ElectricalModelConfig,normalizeElectricalModelRegistry} from '@/lib/electrical-model-registry';
import {OEM_SOURCES} from '@/lib/oem-source-catalog';
import {OEM_CAD_CANDIDATES} from '@/lib/oem-cad-candidates';

const box:React.CSSProperties={border:'1px solid #173a4c',background:'#08151f',borderRadius:14,padding:16};
const field:React.CSSProperties={width:'100%',background:'#061019',border:'1px solid #1d465a',borderRadius:8,color:'#d9eef7',padding:'9px 10px'};
const btn:React.CSSProperties={background:'#163146',border:'1px solid #245b73',borderRadius:9,color:'#d9eef7',padding:'9px 12px',cursor:'pointer'};

export default function ModelRegistryManager(){
 const [registry,setRegistry]=useState<ElectricalModelConfig[]>(DEFAULT_ELECTRICAL_MODEL_REGISTRY);
 const [query,setQuery]=useState('');
 const [category,setCategory]=useState('ALL');
 const [selected,setSelected]=useState(ELECTRICAL_COMPONENTS[0]?.key||'');
 const [message,setMessage]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(ELECTRICAL_MODEL_REGISTRY_STORAGE_KEY);if(raw)setRegistry(normalizeElectricalModelRegistry(JSON.parse(raw)));}catch{}const select=(event:Event)=>{const key=(event as CustomEvent<{componentKey:string}>).detail?.componentKey;if(ELECTRICAL_COMPONENTS.some(component=>component.key===key))setSelected(key)};window.addEventListener('stratum:select-model-registry',select);return()=>window.removeEventListener('stratum:select-model-registry',select)},[]);
 const current=registry.find(x=>x.componentKey===selected)||registry[0];
 const component=ELECTRICAL_COMPONENTS.find(x=>x.key===selected);
 const mapped=registry.filter(x=>x.modelUrl.trim()).length;
 const dimensioned=registry.filter(x=>x.dimensionsMeters?.every(value=>value>0)).length;
 const visible=useMemo(()=>ELECTRICAL_COMPONENTS.filter(c=>(category==='ALL'||c.category===category)&&(!query||`${c.name} ${c.aliases.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
 function persist(next:ElectricalModelConfig[]){setRegistry(next);localStorage.setItem(ELECTRICAL_MODEL_REGISTRY_STORAGE_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('stratum:model-registry-updated',{detail:next}));}
 function patch(update:Partial<ElectricalModelConfig>){if(!current)return;persist(registry.map(x=>x.componentKey===current.componentKey?{...x,...update}:x));}
 function tuplePatch(key:'rotation'|'offset',index:number,value:string){if(!current)return;const copy=[...current[key]] as [number,number,number];copy[index]=Number(value)||0;patch({[key]:copy} as any);}
 function dimensionPatch(index:number,value:string){if(!current)return;const copy=[...(current.dimensionsMeters||[0,0,0])] as [number,number,number];copy[index]=Math.max(0,Number(value)||0);patch({dimensionsMeters:copy});}
 function reset(){persist(DEFAULT_ELECTRICAL_MODEL_REGISTRY);setMessage('Registry reset to shipped model mappings. Spatial renderer notified.');}
 function exportJson(){const blob=new Blob([JSON.stringify(registry,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='stratum-electrical-model-registry.json';a.click();URL.revokeObjectURL(url);}
 async function importJson(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const next=normalizeElectricalModelRegistry(JSON.parse(await file.text()));persist(next);setMessage(`Imported ${next.filter(x=>x.modelUrl).length} mapped 3D models and ${next.filter(x=>x.dimensionsMeters).length} dimension profiles. Spatial renderer notified.`);}catch{setMessage('Registry import failed: invalid JSON.');}e.target.value='';}
 return <section id="spatial-3d-asset-registry" style={{...box,marginTop:18}} aria-label="3D Asset Registry">
  <div style={{display:'flex',gap:16,justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap'}}>
   <div><span style={{color:'#38e59c',fontWeight:800,letterSpacing:2,fontSize:12}}>SPATIAL 3D ASSET REGISTRY</span><h2 style={{margin:'6px 0'}}>Models + physical dimensions</h2><p style={{maxWidth:850,color:'#89a9b8',margin:0}}>Map a detailed 3D model and, when available, OEM/spec width, height and depth in meters. STRATUM uses physical dimensions ahead of nominal procedural geometry; source placement and review authority remain separate.</p></div>
   <div style={{display:'flex',gap:14,alignItems:'center',flexWrap:'wrap'}}><span><strong style={{fontSize:28}}>{mapped}</strong><small style={{display:'block',color:'#89a9b8'}}>models mapped</small></span><span><strong style={{fontSize:28}}>{dimensioned}</strong><small style={{display:'block',color:'#89a9b8'}}>dimensioned</small></span></div>
  </div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(260px,360px) minmax(0,1fr)',gap:16,marginTop:18}} className="model-registry-grid">
   <div style={box}>
    <input aria-label="Search component models" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search component class…" style={field}/>
    <select aria-label="Filter model category" value={category} onChange={e=>setCategory(e.target.value)} style={{...field,marginTop:8}}><option value="ALL">All categories</option>{ELECTRICAL_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select>
    <div style={{maxHeight:520,overflow:'auto',marginTop:10,display:'grid',gap:6}}>{visible.map(c=>{const cfg=registry.find(x=>x.componentKey===c.key);return <button key={c.key} onClick={()=>setSelected(c.key)} style={{...btn,textAlign:'left',background:selected===c.key?'#0e4438':'#0a1a25'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{c.name}</b><span style={{color:cfg?.modelUrl?'#38e59c':'#6f8995'}}>{cfg?.modelUrl?'MODEL':'FALLBACK'}</span></div><small style={{color:'#7896a3'}}>{c.category}{cfg?.dimensionsMeters?.every(value=>value>0)?' · dimensions':''}</small></button>})}</div>
   </div>
   {current&&component?<div style={box}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 4px'}}>{component.name}</h3><small style={{color:'#7896a3'}}>{component.key} · procedural shape: {component.twinShape}</small></div><b style={{color:current.modelUrl?'#38e59c':'#e2a857'}}>{current.modelUrl?'DETAILED MODEL ACTIVE':'PROCEDURAL FALLBACK'}</b></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 150px 120px',gap:10,marginTop:16}} className="registry-fields"><label>Model URL<input value={current.modelUrl} onChange={e=>patch({modelUrl:e.target.value})} placeholder="/models/electrical/transformer.glb or https://…" style={field}/></label><label>Format<select value={current.format} onChange={e=>patch({format:e.target.value as any})} style={field}><option>GLB</option><option>GLTF</option><option>USD</option><option>USDZ</option></select></label><label>Model scale<input type="number" step="0.01" min="0.01" value={current.scale} onChange={e=>patch({scale:Number(e.target.value)||1})} style={field}/></label></div>

    <fieldset style={{...box,padding:12,marginTop:12}}><legend>Physical dimensions · meters</legend><p style={{color:'#7896a3',margin:'0 0 8px'}}>Use OEM/submittal dimensions when known. These dimensions drive asset height/scale; they do not establish installed Z.</p><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8}}>{['Width','Height','Depth'].map((name,index)=><label key={name}>{name}<input aria-label={`${name} dimension meters`} type="number" min="0" step="0.001" value={current.dimensionsMeters?.[index]||''} onChange={e=>dimensionPatch(index,e.target.value)} placeholder="m" style={field}/></label>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 140px',gap:8,marginTop:8}} className="registry-fields"><label>Dimension source<input aria-label="Dimension source" value={current.dimensionsSource||''} onChange={e=>patch({dimensionsSource:e.target.value})} placeholder="OEM submittal, manufacturer datasheet, approved schedule…" style={field}/></label><label>Confidence<input aria-label="Dimension confidence" type="number" min="0" max="1" step="0.05" value={current.dimensionsConfidence??.85} onChange={e=>patch({dimensionsConfidence:Math.max(0,Math.min(1,Number(e.target.value)||0))})} style={field}/></label></div></fieldset>

    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:12}} className="registry-fields"><fieldset style={{...box,padding:12}}><legend>Rotation °</legend><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8}}>{['X','Y','Z'].map((n,i)=><label key={n}>{n}<input type="number" value={current.rotation[i]} onChange={e=>tuplePatch('rotation',i,e.target.value)} style={field}/></label>)}</div></fieldset><fieldset style={{...box,padding:12}}><legend>Position offset</legend><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8}}>{['X','Y','Z'].map((n,i)=><label key={n}>{n}<input type="number" step="0.01" value={current.offset[i]} onChange={e=>tuplePatch('offset',i,e.target.value)} style={field}/></label>)}</div></fieldset></div>
    <div style={{display:'grid',gridTemplateColumns:'150px 1fr',gap:10,marginTop:12}} className="registry-fields"><label>LOD<select value={current.lod||'MEDIUM'} onChange={e=>patch({lod:e.target.value as any})} style={field}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Model source / license<input value={current.source||''} onChange={e=>patch({source:e.target.value})} placeholder="Manufacturer BIM, STRATUM model, licensed source…" style={field}/></label></div>
    <div style={{...box,marginTop:12}}><strong>OEM sources linked to this 3D registry class</strong><p style={{color:'#89a9b8',fontSize:12}}>These links help identify the exact product. The active 3D file and its geometry origin are shown separately.</p>{(current.oemSourceIds||[]).length?<ul style={{paddingLeft:20}}>{current.oemSourceIds!.map(id=>{const source=OEM_SOURCES.find(item=>item.id===id);return source?<li key={id}><a href={source.url} target="_blank" rel="noopener noreferrer" style={{color:'#6cd6fa'}}>{source.manufacturer} · {source.families.join(', ')}</a></li>:null})}</ul>:<p style={{color:'#89a9b8'}}>No researched OEM source associated yet.</p>}<p><b>3D mapping:</b> {current.modelUrl?current.geometryStatus==='LICENSED_COMMUNITY'?'Licensed community visualization':current.geometryStatus==='OEM_SUPPLIED'?'OEM supplied geometry':'STRATUM representative visualization':'No model file mapped'} · <b>Model file:</b> {current.modelUrl||'pending'}</p>{current.sourceUrl&&<a href={current.sourceUrl} target="_blank" rel="noopener noreferrer" style={{color:'#6cd6fa'}}>Model evidence / original source ↗</a>}</div>
    {OEM_CAD_CANDIDATES.some(item=>item.componentKey===current.componentKey)&&<div style={{...box,marginTop:12}}><strong>Exact OEM CAD acquisition</strong><p style={{color:'#89a9b8',fontSize:12}}>These product records are candidates only. They are not the active model until a CAD file is obtained, converted, checked and approved for reuse.</p><ul style={{paddingLeft:20}}>{OEM_CAD_CANDIDATES.filter(item=>item.componentKey===current.componentKey).map(item=><li key={item.id}><a href={item.productUrl} target="_blank" rel="noopener noreferrer" style={{color:'#6cd6fa'}}>{item.manufacturer} {item.sku}</a> · {item.cadFormat} · {item.status==='CAD_DOWNLOAD_IDENTIFIED'?'download identified':'product identified'}; viewer file pending</li>)}</ul></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:12}} className="registry-fields"><label>Original model/source URL<input aria-label="Original model source URL" value={current.sourceUrl||''} onChange={e=>patch({sourceUrl:e.target.value})} placeholder="OEM model or original creator URL" style={field}/></label><label>Model reuse license<input aria-label="Model reuse license" value={current.license||''} onChange={e=>patch({license:e.target.value})} placeholder="License and attribution" style={field}/></label></div>
    <label style={{display:'block',marginTop:12}}>Notes<textarea value={current.notes||''} onChange={e=>patch({notes:e.target.value})} rows={3} style={field}/></label>
    <div style={{display:'flex',gap:8,marginTop:14,flexWrap:'wrap'}}><button style={btn} onClick={exportJson}>Export registry</button><label style={{...btn,display:'inline-block'}}>Import registry<input type="file" accept="application/json,.json" onChange={importJson} hidden/></label><button style={btn} onClick={reset}>Reset fallbacks</button></div>{message&&<p style={{color:'#38e59c'}}>{message}</p>}
   </div>:null}
  </div>
  <style jsx global>{`@media(max-width:900px){.model-registry-grid{grid-template-columns:1fr!important}.registry-fields{grid-template-columns:1fr!important}}`}</style>
 </section>;
}
