'use client';
import {useEffect,useRef,useState} from 'react';
import {drawingMarkEntity,type DrawingMark} from '../lib/drawing-review';
import {readPrimarySpatialGraph,replaceCurrentSpatialGraph} from '../lib/spatial-browser-recovery';

type SourceRecord={source:string;image?:string;marks:DrawingMark[];pageCount?:number};
const legacyMark=(m:Partial<DrawingMark>):DrawingMark=>({id:m.id||crypto.randomUUID(),page:m.page||1,x:m.x||0,y:m.y||0,width:m.width||20,height:m.height||14,label:m.label||'',reference:m.reference||'',legend:m.legend||'',component:m.component||'unresolved',drawingState:m.drawingState||'unresolved'});
export default function PlanAnnotations(){
 const [url,setUrl]=useState(''),[source,setSource]=useState(''),[digest,setDigest]=useState('');
 const [marks,setMarks]=useState<DrawingMark[]>([]),[label,setLabel]=useState(''),[reference,setReference]=useState(''),[legend,setLegend]=useState('');
 const [component,setComponent]=useState<DrawingMark['component']>('unresolved'),[drawingState,setDrawingState]=useState<DrawingMark['drawingState']>('unresolved');
 const [message,setMessage]=useState(''),[savedPlans,setSavedPlans]=useState<{digest:string;source:string}[]>([]);
 const [page,setPage]=useState(1),[pageCount,setPageCount]=useState(1),[width,setWidth]=useState(20),[height,setHeight]=useState(14),[isPdf,setIsPdf]=useState(false),[zoom,setZoom]=useState(1);
 const pdf=useRef<any>(null),renderId=useRef(0);
 async function refreshPlans(){try{const graph=await readPrimarySpatialGraph();const plans=new Map<string,string>();for(const [key,value] of Object.entries((graph?.annotationSources||{}) as Record<string,SourceRecord>))plans.set(key,value.source);setSavedPlans([...plans].map(([digest,source])=>({digest,source})));}catch{setMessage('Some saved plans could not be read. Existing data has been preserved.');}}
 useEffect(()=>{void refreshPlans();return()=>{renderId.current++;void pdf.current?.destroy?.()};},[]);
 async function savedPlan(hash:string):Promise<SourceRecord|undefined>{const graph=await readPrimarySpatialGraph();return (graph?.annotationSources as Record<string,SourceRecord>|undefined)?.[hash]}
 async function restore(hash:string){const record=await savedPlan(hash);if(!record){setMessage('This saved plan could not be restored.');return}renderId.current++;void pdf.current?.destroy?.();pdf.current=null;setDigest(hash);setSource(record.source);setMarks(Array.isArray(record.marks)?record.marks.map(legacyMark):[]);setPage(1);setPageCount(record.pageCount||1);setIsPdf(record.source.toLowerCase().endsWith('.pdf'));setUrl(record.image||'');setMessage(record.image?'Saved image restored.':'Review marks restored. Reattach the same PDF to view its pages; its SHA-256 fingerprint will match the saved marks.');}
 async function renderPage(doc:any,target:number){const request=++renderId.current;setUrl('');setMessage(`Rendering page ${target} of ${doc.numPages}…`);try{const pdfPage=await doc.getPage(target);const base=pdfPage.getViewport({scale:1});const viewport=pdfPage.getViewport({scale:Math.min(3,2400/Math.max(base.width,base.height))});const canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');await pdfPage.render({canvasContext:ctx,viewport}).promise;if(request!==renderId.current)return;setPage(target);setWidth(base.width);setHeight(base.height);setUrl(canvas.toDataURL('image/jpeg',.82));setMessage(`Page ${target} rendered. Enter the printed tag, then click its symbol.`);pdfPage.cleanup();}catch{if(request===renderId.current)setMessage('This PDF page could not be rendered. Existing marks were preserved.');}}
 async function upload(file:File){if(!/\.pdf$|\.png$|\.jpe?g$/i.test(file.name)){setMessage('Choose a PDF, PNG or JPEG drawing.');return}try{const bytes=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);const fingerprint=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');const saved=await savedPlan(fingerprint);renderId.current++;await pdf.current?.destroy?.();pdf.current=null;setDigest(fingerprint);setSource(file.name);setMarks(Array.isArray(saved?.marks)?saved!.marks.map(legacyMark):[]);const pdfFile=/\.pdf$/i.test(file.name);setIsPdf(pdfFile);setPage(1);
 if(pdfFile){const PromiseWithResolvers=Promise as any;if(typeof PromiseWithResolvers.withResolvers!=='function')PromiseWithResolvers.withResolvers=()=>{let resolve:any,reject:any;const promise=new Promise((ok,fail)=>{resolve=ok;reject=fail});return{promise,resolve,reject}};const mod:any=await import('pdfjs-dist/legacy/build/pdf.mjs');mod.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();const doc=await mod.getDocument({data:new Uint8Array(bytes),wasmUrl:'/pdfjs/wasm/'}).promise;pdf.current=doc;setPageCount(doc.numPages);await renderPage(doc,1)}else{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});const img=new Image();img.src=data;await img.decode();setWidth(img.naturalWidth);setHeight(img.naturalHeight);setPageCount(1);setUrl(data);setMessage('Enter the printed tag, then click its symbol. This records a review candidate.')}}catch{setMessage('Could not read the drawing. Existing marks remain on screen.')}}
 async function publish(){if(!digest||!url)return;try{const existing=await readPrimarySpatialGraph();const graph:any=existing?structuredClone(existing):{version:'1.1',sources:[],entities:[],links:[],stats:{}};
 const entities=marks.map(mark=>drawingMarkEntity(mark,digest,source));graph.entities=[...graph.entities.filter((e:{id:string})=>!e.id.startsWith(`${digest}:annotation:`)),...entities];const retained=new Set(graph.entities.map((e:{id:string})=>e.id));graph.links=(graph.links||[]).filter((link:{from:string;to:string})=>retained.has(link.from)&&retained.has(link.to));graph.stats=graph.stats||{};if(!graph.sources.some((s:{sha256:string})=>s.sha256===digest))graph.sources.push({name:source,sha256:digest,ext:source.split('.').pop()?.toLowerCase(),discipline:'Unclassified',floor:'UNRESOLVED',elevation:0});graph.createdAt=new Date().toISOString();for(const layer of ['L0','L1','L2','L3','L4'])graph.stats[layer]=layer==='L0'?graph.sources.length:graph.entities.filter((e:{layer:string})=>e.layer===layer).length;
 graph.annotationSources={...graph.annotationSources,[digest]:{source,marks,pageCount,...(!isPdf?{image:url}:{})}};
 await replaceCurrentSpatialGraph(graph);await refreshPlans();setMessage('Drawing candidates saved in this browser and added to Spatial. PDF page images are not saved; reattach the source to review its pages. Authentication is required for server sync.');}catch(error){setMessage(error instanceof Error?`Save failed: ${error.message}`:'Save failed. Your review marks remain on screen.')}}
 const pageMarks=marks.filter(m=>m.page===page);
 return <details className="card compiler-exception" style={{marginBottom:16}}><summary><span><strong>Drawing symbol review</strong><small>Review PDF or image symbols missed by automatic extraction.</small></span><span className="pending">OPTIONAL</span></summary><div className="compiler-exception-body"><p className="muted">Use this sheet’s legend or equipment schedule to classify a symbol. An annotation is a review candidate: it does not establish installation, 3D dimensions, a registered asset or maintenance history.</p><label>Saved drawing<select aria-label="Saved plan" value={savedPlans.some(p=>p.digest===digest)?digest:''} onChange={e=>{if(e.target.value)void restore(e.target.value)}}><option value="">Choose a saved drawing</option>{savedPlans.map(p=><option key={p.digest} value={p.digest}>{p.source}</option>)}</select></label><input aria-label="Drawing PDF or image" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/>
 {isPdf&&pageCount>1&&<label>PDF page<select aria-label="PDF page" value={page} onChange={e=>{const target=Number(e.target.value);if(pdf.current)void renderPage(pdf.current,target)}}>{Array.from({length:pageCount},(_,i)=><option key={i+1} value={i+1}>Page {i+1}</option>)}</select></label>}
 {url&&<label>Sheet zoom<select aria-label="Sheet zoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={1}>Fit width</option><option value={2}>2×</option><option value={3}>3×</option></select></label>}
 <div className="button-row"><input aria-label="Printed tag" placeholder="Printed tag, e.g. L5A" value={label} onChange={e=>setLabel(e.target.value)}/><input aria-label="Drawing reference" placeholder="Sheet/detail, e.g. E4.0" value={reference} onChange={e=>setReference(e.target.value)}/></div>
 <div className="button-row"><select aria-label="Symbol type" value={component} onChange={e=>setComponent(e.target.value as DrawingMark['component'])}><option value="unresolved">Type unresolved</option><option value="panel">Panel</option><option value="switch">Switch</option><option value="receptacle">Receptacle</option><option value="other">Other equipment</option></select><input aria-label="Legend or schedule evidence" placeholder="Legend / schedule reference to classify" value={legend} onChange={e=>setLegend(e.target.value)}/><select aria-label="Drawing state" value={drawingState} onChange={e=>setDrawingState(e.target.value as DrawingMark['drawingState'])}><option value="unresolved">Drawing state unresolved</option><option value="existing">Drawing says existing</option><option value="new">Drawing says new</option></select></div>
 {url&&<div style={{overflowX:'auto',marginTop:12}}><div style={{position:'relative',width:`${zoom*100}%`}}><img src={url} alt={`${source}, page ${page}`} style={{width:'100%',display:'block',cursor:'crosshair'}} onClick={e=>{if(!label.trim()){setMessage('Enter the printed tag first.');return}if(component!=='unresolved'&&!legend.trim()){setMessage('To classify a symbol, enter its sheet legend or schedule reference.');return}const r=e.currentTarget.getBoundingClientRect();setMarks(v=>[...v,{id:crypto.randomUUID(),page,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,width,height,label:label.trim(),reference:reference.trim(),legend:legend.trim(),component,drawingState}]);}}/>{pageMarks.map((m,i)=><span key={m.id} title={`${m.label} ${m.reference}`} style={{position:'absolute',left:`${m.x*100}%`,top:`${m.y*100}%`,background:'#063e54',color:'white',border:'2px solid cyan',borderRadius:20,padding:'2px 6px',pointerEvents:'none',transform:'translate(-50%,-50%)'}}>{i+1}</span>)}</div></div>}
 <ol>{marks.map(m=><li key={m.id}>Page {m.page} · {m.label} · {m.component} · {m.reference||'No detail reference'} <button onClick={()=>setMarks(v=>v.filter(x=>x.id!==m.id))}>Remove</button></li>)}</ol><button disabled={!digest||!url} onClick={()=>void publish()}>Save drawing candidates to Spatial</button><p role="status">{message}</p></div></details>
}
