'use client';
import {useEffect,useState} from 'react';
type Mark={id:string;x:number;y:number;label:string;reference:string};
export default function PlanAnnotations(){
 const [url,setUrl]=useState(''),[source,setSource]=useState(''),[digest,setDigest]=useState(''),[marks,setMarks]=useState<Mark[]>([]),[label,setLabel]=useState(''),[reference,setReference]=useState(''),[message,setMessage]=useState('');
 const [savedPlans,setSavedPlans]=useState<{digest:string;source:string}[]>([]);
 function refreshPlans(){try{const graph=JSON.parse(localStorage.getItem('stratum_compiled_graph')||'{}');const plans=new Map<string,string>();for(const [key,value] of Object.entries(graph.annotationSources||{}))plans.set(key,(value as {source:string}).source);for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)||'';if(key.startsWith('stratum_annotation_source:')){const record=JSON.parse(localStorage.getItem(key)||'{}');if(record.source)plans.set(key.split(':')[1],record.source);}}setSavedPlans([...plans].map(([digest,source])=>({digest,source})));}catch{setMessage('Some saved plans could not be read. Existing data has been preserved.');}}
 useEffect(refreshPlans,[]);
 function savedPlan(hash:string){const graph=JSON.parse(localStorage.getItem('stratum_compiled_graph')||'{}');return graph.annotationSources?.[hash]||JSON.parse(localStorage.getItem(`stratum_annotation_source:${hash}`)||'null');}
 function restore(hash:string){try{const record=savedPlan(hash);if(!record||!Array.isArray(record.marks)||!record.image)throw new Error();setDigest(hash);setSource(record.source);setUrl(record.image);setMarks(record.marks);setMessage('Saved plan restored. Changes are applied when you save annotations.');}catch{setMessage('This saved plan could not be restored.');}}
 async function upload(file:File){try{const bytes=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});const fingerprint=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');const saved=savedPlan(fingerprint);setDigest(fingerprint);setSource(file.name);setUrl(data);setMarks(Array.isArray(saved?.marks)?saved.marks:[]);setMessage('Enter the callout, then click its equipment target. Placement is manually recorded in image coordinates.');}catch{setMessage('Could not read this image.');}}
 function publish(){try{const raw=localStorage.getItem('stratum_compiled_graph');const graph=raw?JSON.parse(raw):{version:'1.1',sources:[],entities:[],links:[],stats:{}};const entities=marks.map(m=>({id:`${digest}:annotation:${m.id}`,source,layer:'L2',kind:'annotated-asset-candidate',name:m.label,x:(m.x-.5)*20,y:(m.y-.5)*14,z:0,floor:'UNRESOLVED',confidence:1,meta:{sourceSha256:digest,sourceType:'MANUAL_IMAGE_ANNOTATION',normalizedX:m.x,normalizedY:m.y,reference:m.reference,reviewRequired:true,registrationState:'CANDIDATE',coordinateUnits:'normalized-sheet',description:m.label}}));graph.entities=[...graph.entities.filter((e:{id:string})=>!e.id.startsWith(`${digest}:annotation:`)),...entities];const retained=new Set(graph.entities.map((e:{id:string})=>e.id));graph.links=(graph.links||[]).filter((link:{from:string;to:string})=>retained.has(link.from)&&retained.has(link.to));graph.stats=graph.stats||{};if(!graph.sources.some((s:{sha256:string})=>s.sha256===digest))graph.sources.push({name:source,sha256:digest,ext:source.split('.').pop(),discipline:'Unclassified',floor:'UNRESOLVED',elevation:0});graph.createdAt=new Date().toISOString();for(const layer of ['L0','L1','L2','L3','L4'])graph.stats[layer]=layer==='L0'?graph.sources.length:graph.entities.filter((e:{layer:string})=>e.layer===layer).length;graph.annotationSources={...graph.annotationSources,[digest]:{source,image:url,marks}};localStorage.setItem('stratum_compiled_graph',JSON.stringify(graph));window.dispatchEvent(new Event('stratum:graph-updated'));refreshPlans();setMessage('Annotations saved in this browser and added to Spatial. Floor, scale and physical state remain unresolved.');}catch{setMessage('Save failed: browser storage may be full. Your annotations remain on screen.');}}
 return <details className="card compiler-exception" style={{marginBottom:16}}><summary><span><strong>Manual annotation</strong><small>Only use this when STRATUM could not identify an object from the source.</small></span><span className="pending">OPTIONAL</span></summary><div className="compiler-exception-body"><p className="muted">Attach an image, enter its callout and detail reference, then click the physical object. Manual annotations remain review-required and do not establish Verified state.</p><label>Saved plan<select aria-label="Saved plan" value={savedPlans.some(p=>p.digest===digest)?digest:""} onChange={e=>{if(e.target.value)restore(e.target.value)}}><option value="">Choose a saved plan</option>{savedPlans.map(p=><option key={p.digest} value={p.digest}>{p.source}</option>)}</select></label><input aria-label="Plan image" type="file" accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><div className="button-row"><input aria-label="Annotation text" placeholder="Supercharger cabinet" value={label} onChange={e=>setLabel(e.target.value)}/><input aria-label="Drawing reference" placeholder="Detail reference, e.g. S-501" value={reference} onChange={e=>setReference(e.target.value)}/></div>{url&&<div style={{position:'relative',marginTop:12}}><img src={url} alt={source} style={{width:'100%',display:'block',cursor:'crosshair'}} onClick={e=>{if(!label.trim()){setMessage('Enter an annotation first.');return;}const r=e.currentTarget.getBoundingClientRect();setMarks(v=>[...v,{id:crypto.randomUUID(),x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,label:label.trim(),reference:reference.trim()}]);}}/>{marks.map((m,i)=><span key={m.id} title={`${m.label} ${m.reference}`} style={{position:'absolute',left:`${m.x*100}%`,top:`${m.y*100}%`,background:'#063e54',color:'white',border:'2px solid cyan',borderRadius:20,padding:'2px 6px',pointerEvents:'none',transform:'translate(-50%,-50%)'}}>{i+1}</span>)}</div>}<ol>{marks.map(m=><li key={m.id}>{m.label} · {m.reference||'No detail reference'} <button onClick={()=>setMarks(v=>v.filter(x=>x.id!==m.id))}>Remove</button></li>)}</ol><button disabled={!digest||!url} onClick={publish}>Save annotations to Spatial</button><p role="status">{message}</p></div></details>
}