'use client';
import {useState} from 'react';
type Mark={id:string;x:number;y:number;label:string;reference:string};
export default function PlanAnnotations(){
 const [url,setUrl]=useState(''),[source,setSource]=useState(''),[digest,setDigest]=useState(''),[marks,setMarks]=useState<Mark[]>([]),[label,setLabel]=useState(''),[reference,setReference]=useState(''),[message,setMessage]=useState('');
 async function upload(file:File){try{const bytes=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});setDigest(Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join(''));setSource(file.name);setUrl(data);setMarks([]);setMessage('Enter the callout, then click its equipment target. Placement is manually recorded in image coordinates.');}catch{setMessage('Could not read this image.');}}
 function publish(){try{const raw=localStorage.getItem('stratum_compiled_graph');const graph=raw?JSON.parse(raw):{version:'1.1',sources:[],entities:[],links:[],stats:{}};const entities=marks.map(m=>({id:`${digest}:annotation:${m.id}`,source,layer:'L2',kind:'annotated-asset-candidate',name:m.label,x:(m.x-.5)*20,y:(m.y-.5)*14,z:0,floor:'UNRESOLVED',confidence:1,meta:{sourceSha256:digest,sourceType:'MANUAL_IMAGE_ANNOTATION',normalizedX:m.x,normalizedY:m.y,reference:m.reference,reviewRequired:true,registrationState:'CANDIDATE',coordinateUnits:'normalized-sheet',description:m.label}}));const ids=new Set(entities.map(e=>e.id));graph.entities=[...graph.entities.filter((e:{id:string})=>!ids.has(e.id)),...entities];if(!graph.sources.some((s:{sha256:string})=>s.sha256===digest))graph.sources.push({name:source,sha256:digest,ext:source.split('.').pop(),discipline:'Unclassified',floor:'UNRESOLVED',elevation:0});graph.createdAt=new Date().toISOString();for(const layer of ['L0','L1','L2','L3','L4'])graph.stats[layer]=layer==='L0'?graph.sources.length:graph.entities.filter((e:{layer:string})=>e.layer===layer).length;localStorage.setItem(`stratum_annotation_source:${digest}`,JSON.stringify({source,image:url,marks}));localStorage.setItem('stratum_compiled_graph',JSON.stringify(graph));setMessage('Annotations saved in this browser and added to Spatial. Floor, scale and physical state remain unresolved.');}catch{setMessage('Save failed: browser storage may be full. Your annotations remain on screen.');}}
 return <section className="card" style={{marginBottom:16}}><h2>Plan annotations</h2><p>Attach an image, enter its callout and detail reference, then click the physical object. These are manual annotations awaiting review.</p><input aria-label="Plan image" type="file" accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><div className="button-row"><input aria-label="Annotation text" placeholder="Supercharger cabinet" value={label} onChange={e=>setLabel(e.target.value)}/><input aria-label="Drawing reference" placeholder="Detail reference, e.g. S-501" value={reference} onChange={e=>setReference(e.target.value)}/></div>{url&&<div style={{position:'relative',marginTop:12}}><img src={url} alt={source} style={{width:'100%',display:'block',cursor:'crosshair'}} onClick={e=>{if(!label.trim()){setMessage('Enter an annotation first.');return;}const r=e.currentTarget.getBoundingClientRect();setMarks(v=>[...v,{id:crypto.randomUUID(),x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,label:label.trim(),reference:reference.trim()}]);}}/>{marks.map((m,i)=><span key={m.id} title={`${m.label} ${m.reference}`} style={{position:'absolute',left:`${m.x*100}%`,top:`${m.y*100}%`,background:'#063e54',color:'white',border:'2px solid cyan',borderRadius:20,padding:'2px 6px',pointerEvents:'none',transform:'translate(-50%,-50%)'}}>{i+1}</span>)}</div>}<ol>{marks.map(m=><li key={m.id}>{m.label} · {m.reference||'No detail reference'} <button onClick={()=>setMarks(v=>v.filter(x=>x.id!==m.id))}>Remove</button></li>)}</ol><button disabled={!marks.length} onClick={publish}>Add annotations to Spatial</button><p role="status">{message}</p></section>
}
