'use client';

import {useEffect,useState} from 'react';

type Project={id:string;name:string;client:string;location:string;status:string;progress:number;assets:number;verified:number};
export default function ProjectManager({initial}:{initial:Project[]}){const [items,setItems]=useState<Project[]>(initial);const [open,setOpen]=useState(false);const [form,setForm]=useState({name:'',client:'',location:'',status:'Active'});const [message,setMessage]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem('stratum-project-workspace');if(raw)setItems(JSON.parse(raw));}catch{}},[]);
 function save(next:Project[]){setItems(next);localStorage.setItem('stratum-project-workspace',JSON.stringify(next));}
 function create(){if(!form.name.trim()||!form.client.trim()||!form.location.trim()){setMessage('Project name, client and location are required.');return;}const id=`STR-PRJ-${String(Date.now()).slice(-4)}`;save([{id,name:form.name.trim(),client:form.client.trim(),location:form.location.trim(),status:form.status,progress:0,assets:0,verified:0},...items]);setForm({name:'',client:'',location:'',status:'Active'});setOpen(false);setMessage(`Created ${id} in this tenant workspace.`);}
 function progress(id:string,value:number){save(items.map(p=>p.id===id?{...p,progress:Math.max(0,Math.min(100,value))}:p));}
 function archive(id:string){save(items.map(p=>p.id===id?{...p,status:'Archived'}:p));}
 function restore(){save(initial);setMessage('Reference project set restored.');}
 return <><div className="page-head"><div><div className="eyebrow">Portfolio</div><h1 className="title">Projects</h1><p className="subtitle">Roll asset verification up from equipment to systems, sites and complete project turnover.</p></div><button type="button" className="action" onClick={()=>setOpen(v=>!v)}>{open?'Close':' + New project'}</button></div>{open&&<div className="card" style={{marginBottom:16}}><div className="eyebrow">Create project</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:10}}><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Project name"/><input value={form.client} onChange={e=>setForm(v=>({...v,client:e.target.value}))} placeholder="Client"/><input value={form.location} onChange={e=>setForm(v=>({...v,location:e.target.value}))} placeholder="Location"/><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}><option>Active</option><option>Planning</option><option>Commissioning</option><option>Operations</option></select></div><div className="button-row" style={{marginTop:10}}><button type="button" onClick={create}>Create project</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></div></div>}{message&&<div className="notice" style={{marginBottom:16}}><strong>STATUS</strong><span>{message}</span></div>}<div className="project-grid">{items.map(p=><div className="card project-card" key={p.id}><div className="project-status">{p.status}</div><div className="eyebrow">{p.id}</div><h2>{p.name}</h2><p className="muted">{p.client}<br/>{p.location}</p><div className="progress"><i style={{width:`${p.progress}%`}}/></div><label className="muted" style={{display:'grid',gap:5,marginTop:10}}>Progress<input type="range" min="0" max="100" value={p.progress} onChange={e=>progress(p.id,Number(e.target.value))}/></label><div className="project-kpis"><div><strong>{p.progress}%</strong><span>Project</span></div><div><strong>{p.assets}</strong><span>Assets</span></div><div><strong>{p.verified}</strong><span>Verified</span></div></div><div className="button-row" style={{marginTop:12}}>{p.status!=='Archived'?<button type="button" onClick={()=>archive(p.id)}>Archive</button>:null}</div></div>)}</div><div className="button-row" style={{marginTop:16}}><button type="button" onClick={restore}>Restore reference projects</button></div><p className="muted" style={{marginTop:8}}>This project CRUD surface persists in the browser until the tenant project API/database is connected. It does not pretend local edits are enterprise records.</p></>}
