'use client';
import {useEffect,useState} from 'react';
import {applySheetTransform,restoreSheetCoordinates,solveSheetTransform,type DrawingEntity} from '../lib/sheet-alignment';
const STORAGE='stratum_compiled_graph';
type Entity=DrawingEntity&{layer:string};
export default function SheetReview(){
 const [entities,setEntities]=useState<Entity[]>([]),[sheet,setSheet]=useState(''),[selected,setSelected]=useState(''),[name,setName]=useState(''),[floor,setFloor]=useState(''),[elevation,setElevation]=useState(''),[coordinates,setCoordinates]=useState<string[]>(Array(8).fill('')),[message,setMessage]=useState('');
 const key=(e:Entity)=>`${e.meta?.sourceSha256||e.source}::${e.meta?.page}`;
 useEffect(()=>{const restore=()=>{try{setEntities(JSON.parse(localStorage.getItem(STORAGE)||'{}').entities||[])}catch{setMessage('Saved drawing could not be read.')}};restore();window.addEventListener('stratum:graph-updated',restore);return()=>window.removeEventListener('stratum:graph-updated',restore)},[]);
 const sheets=[...new Map(entities.filter(e=>e.meta?.page).map(e=>[key(e),`${e.source} · page ${e.meta?.page}`])).entries()];
 const current=entities.filter(e=>key(e)===sheet),boundaries=current.filter(e=>e.vertices?.length),chosen=current.find(e=>e.id===selected);
 const points=boundaries.flatMap(e=>e.vertices||[]),xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=points.length?Math.min(...xs):-10,minY=points.length?Math.min(...ys):-7,w=points.length?Math.max(...xs)-minX:20,h=points.length?Math.max(...ys)-minY:14;
 function save(change:(e:Entity)=>Entity){try{const graph=JSON.parse(localStorage.getItem(STORAGE)||'{}');if(!Array.isArray(graph.entities))throw new Error('No saved drawing');const next={...graph,entities:graph.entities.map(change)};localStorage.setItem(STORAGE,JSON.stringify(next));window.dispatchEvent(new Event('stratum:graph-updated'));setMessage('Drawing review saved in this browser. Engineering approval remains separate.');}catch(error){setMessage(`Save failed: ${error instanceof Error?error.message:'Storage unavailable'}. Existing saved work is unchanged.`);}}
 function align(){try{if(coordinates.some(value=>!value.trim())||!elevation.trim())throw new Error('Enter all control coordinates and the measured elevation.');const n=coordinates.map(Number),t=solveSheetTransform([{x:n[0],y:n[1]},{x:n[2],y:n[3]}],[{x:n[4],y:n[5]},{x:n[6],y:n[7]}],floor,Number(elevation));save(e=>key(e)===sheet?applySheetTransform(e,t):e);}catch(error){setMessage(error instanceof Error?error.message:'Alignment failed')}}
 if(!sheets.length)return null;
 return <section className="card" style={{marginBottom:16}} aria-label="Drawing review"><h2>Sheet geometry review and alignment</h2><p>Review extracted closed paths against the original drawing. A closed path can be a symbol or sheet border; it is not automatically a room. Coordinates below are extracted sheet coordinates until calibrated.</p>
 <label>Drawing sheet<select value={sheet} onChange={e=>{setSheet(e.target.value);setSelected('');setName('');setMessage('');setCoordinates(Array(8).fill(''));setFloor('');setElevation('')}}><option value="">Choose a sheet</option>{sheets.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {sheet&&<><svg role="img" aria-label="Extracted sheet boundary candidates" viewBox={`${minX-1} ${-minY-h-1} ${Math.max(w,1)+2} ${Math.max(h,1)+2}`} style={{width:'100%',height:360,background:'#07131f'}}>{boundaries.map(e=><polygon transform="scale(1,-1)" key={e.id} points={e.vertices!.map(p=>`${p.x},${p.y}`).join(' ')} fill={e.id===selected?'#2684aa55':'transparent'} stroke={e.id===selected?'#7de7ff':'#547d91'} strokeWidth={Math.max(w,h)/800} onClick={()=>{setSelected(e.id);setName(e.name)}}><title>{e.name}</title></polygon>)}</svg>
 <label>Boundary<select value={selected} onChange={e=>{setSelected(e.target.value);setName(current.find(item=>item.id===e.target.value)?.name||'')}}><option value="">Choose a boundary</option>{boundaries.map(e=><option key={e.id} value={e.id}>{e.name} · {e.id.slice(-18)}</option>)}</select></label>
 {chosen?.vertices&&<details><summary>Original boundary control coordinates</summary><table><thead><tr><th>Point</th><th>Sheet X</th><th>Sheet Y</th></tr></thead><tbody>{((chosen.meta?.sheetOriginal as DrawingEntity|undefined)?.vertices||chosen.vertices).map((p,i)=><tr key={i}><td>{i+1}</td><td>{p.x.toFixed(6)}</td><td>{p.y.toFixed(6)}</td></tr>)}</tbody></table></details>}
 <label>Reviewed room name<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!chosen?.vertices||!name.trim()} onClick={()=>save(e=>e.id===selected?{...e,kind:'room-boundary',name:name.trim(),meta:{...e.meta,reviewRequired:false,geometryValidated:true,geometryReview:'manual-boundary-review',reviewedAt:new Date().toISOString()}}:e)}>Confirm selected boundary as room</button>
 <button disabled={chosen?.kind!=='room-boundary'} onClick={()=>save(e=>e.id===selected?{...e,kind:'vector-boundary-candidate',meta:{...e.meta,geometryValidated:false,reviewRequired:true}}:e)}>Undo room confirmation</button>
 <p>Use two corresponding points from the original sheet frame and your shared project coordinate system. Reapplying alignment always starts from the original coordinates. Check a third known point independently before accepting engineering accuracy.</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{['Sheet A X','Sheet A Y','Sheet B X','Sheet B Y','Project A X (m)','Project A Y (m)','Project B X (m)','Project B Y (m)'].map((label,i)=><label key={label}>{label}<input type="number" step="any" value={coordinates[i]} onChange={e=>setCoordinates(old=>old.map((v,j)=>i===j?e.target.value:v))}/></label>)}<label>Floor identifier<input value={floor} onChange={e=>setFloor(e.target.value)} placeholder="L2"/></label><label>Measured elevation (m)<input type="number" step="any" value={elevation} onChange={e=>setElevation(e.target.value)}/></label></div><button onClick={align}>Apply sheet alignment</button><button onClick={()=>save(e=>key(e)===sheet?restoreSheetCoordinates(e):e)}>Restore original sheet coordinates</button></>}
 <p role="status">{message}</p></section>;
}
