'use client';
import {useEffect,useState} from 'react';
import {applySheetTransform,restoreSheetCoordinates,solveSheetTransform,type DrawingEntity} from '../lib/sheet-alignment';
import {readPrimarySpatialGraph,replaceCurrentSpatialGraph} from '../lib/spatial-browser-recovery';
type AutoRoomProposal={name?:string|null;confidence?:number;eligible?:boolean;reasons?:string[]};
type Entity=DrawingEntity&{layer:string};
const proposalFor=(entity:Entity|undefined)=>(entity?.meta?.automaticRoomProposal||null) as AutoRoomProposal|null;
const reviewName=(entity:Entity|undefined)=>{const proposal=proposalFor(entity);return proposal?.eligible&&proposal.name?proposal.name:entity?.name||''};
export default function SheetReview(){
 const [entities,setEntities]=useState<Entity[]>([]),[sheet,setSheet]=useState(''),[selected,setSelected]=useState(''),[name,setName]=useState(''),[floor,setFloor]=useState(''),[elevation,setElevation]=useState(''),[coordinates,setCoordinates]=useState<string[]>(Array(8).fill('')),[message,setMessage]=useState('');
 const key=(e:Entity)=>`${e.meta?.sourceSha256||e.source}::${e.meta?.page}`;
 useEffect(()=>{let active=true;const restore=async()=>{try{const graph=await readPrimarySpatialGraph();if(active)setEntities((graph?.entities||[]) as Entity[])}catch{if(active)setMessage('Saved drawing could not be read.')}};const run=()=>{void restore()};run();window.addEventListener('stratum:graph-updated',run);return()=>{active=false;window.removeEventListener('stratum:graph-updated',run)}},[]);
 const sheets=[...new Map(entities.filter(e=>e.meta?.page).map(e=>[key(e),`${e.source} · page ${e.meta?.page}`])).entries()];
 const current=entities.filter(e=>key(e)===sheet),boundaries=current.filter(e=>e.vertices?.length),chosen=current.find(e=>e.id===selected),chosenProposal=proposalFor(chosen);
 const points=boundaries.flatMap(e=>e.vertices||[]),xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=points.length?Math.min(...xs):-10,minY=points.length?Math.min(...ys):-7,w=points.length?Math.max(...xs)-minX:20,h=points.length?Math.max(...ys)-minY:14;
 async function save(change:(e:Entity)=>Entity){try{const graph=await readPrimarySpatialGraph();if(!graph||!Array.isArray(graph.entities))throw new Error('No saved drawing');const next={...graph,entities:(graph.entities as Entity[]).map(change)};await replaceCurrentSpatialGraph(next);setMessage('Drawing review saved in this browser. Engineering approval remains separate.');}catch(error){setMessage(`Save failed: ${error instanceof Error?error.message:'Storage unavailable'}. Existing saved work is unchanged.`);}}
 async function align(){try{if(coordinates.some(value=>!value.trim())||!elevation.trim())throw new Error('Enter all control coordinates and the measured elevation.');const n=coordinates.map(Number),t=solveSheetTransform([{x:n[0],y:n[1]},{x:n[2],y:n[3]}],[{x:n[4],y:n[5]},{x:n[6],y:n[7]}],floor,Number(elevation));await save(e=>key(e)===sheet?applySheetTransform(e,t):e);}catch(error){setMessage(error instanceof Error?error.message:'Alignment failed')}}
 if(!sheets.length)return null;
 return <details role="region" className="card compiler-exception" style={{marginBottom:16}} aria-label="Drawing review"><summary><span><strong>Review drawing geometry</strong><small>{sheets.length} sheet{sheets.length===1?'':'s'} with extracted drawing data. Open only when geometry, room identity, floor or alignment needs review.</small></span><span className="pending">REVIEW IF NEEDED</span></summary><div className="compiler-exception-body"><p className="muted">STRATUM may propose a room when geometry and a contained source label pass deterministic checks, but a proposal is not a reviewed room until you confirm it here. Coordinates remain extracted sheet coordinates until calibrated.</p>
 <label>Drawing sheet<select value={sheet} onChange={e=>{setSheet(e.target.value);setSelected('');setName('');setMessage('');setCoordinates(Array(8).fill(''));setFloor('');setElevation('')}}><option value="">Choose a sheet</option>{sheets.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {sheet&&<><svg role="img" aria-label="Extracted sheet boundary candidates" viewBox={`${minX-1} ${-minY-h-1} ${Math.max(w,1)+2} ${Math.max(h,1)+2}`} style={{width:'100%',height:360,background:'#07131f'}}>{boundaries.map(e=><polygon transform="scale(1,-1)" key={e.id} points={e.vertices!.map(p=>`${p.x},${p.y}`).join(' ')} fill={e.id===selected?'#2684aa55':'transparent'} stroke={e.id===selected?'#7de7ff':'#547d91'} strokeWidth={Math.max(w,h)/800} onClick={()=>{setSelected(e.id);setName(reviewName(e))}}><title>{proposalFor(e)?.eligible?`${proposalFor(e)?.name||e.name} · automatic room proposal ${Math.round((proposalFor(e)?.confidence||0)*100)}%`:e.name}</title></polygon>)}</svg>
 <label>Boundary<select value={selected} onChange={e=>{const next=current.find(item=>item.id===e.target.value);setSelected(e.target.value);setName(reviewName(next))}}><option value="">Choose a boundary</option>{boundaries.map(e=>{const proposal=proposalFor(e);return <option key={e.id} value={e.id}>{proposal?.eligible?`ROOM PROPOSAL ${Math.round((proposal.confidence||0)*100)}% · ${proposal.name||e.name}`:e.name} · {e.id.slice(-18)}</option>})}</select></label>
 {chosenProposal&&<div className="notice"><strong>{chosenProposal.eligible?'AUTOMATIC ROOM PROPOSAL':'RECONSTRUCTION REVIEW'}</strong><span>{chosenProposal.eligible?`${chosenProposal.name} · confidence ${Math.round((chosenProposal.confidence||0)*100)}% · human confirmation required`:(chosenProposal.reasons||[]).join(' ')}</span></div>}
 {chosen?.vertices&&<details><summary>Original boundary control coordinates</summary><table><thead><tr><th>Point</th><th>Sheet X</th><th>Sheet Y</th></tr></thead><tbody>{((chosen.meta?.sheetOriginal as DrawingEntity|undefined)?.vertices||chosen.vertices).map((p,i)=><tr key={i}><td>{i+1}</td><td>{p.x.toFixed(6)}</td><td>{p.y.toFixed(6)}</td></tr>)}</tbody></table></details>}
 <label>Reviewed room name<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!chosen?.vertices||!name.trim()} onClick={()=>void save(e=>e.id===selected?{...e,kind:'room-boundary',name:name.trim(),meta:{...e.meta,reviewRequired:false,geometryValidated:true,geometryReview:'manual-boundary-review',automaticProposalAccepted:Boolean(chosenProposal?.eligible),reviewedAt:new Date().toISOString()}}:e)}>Confirm selected boundary as room</button>
 <button disabled={chosen?.kind!=='room-boundary'} onClick={()=>void save(e=>e.id===selected?{...e,kind:'vector-boundary-candidate',meta:{...e.meta,geometryValidated:false,reviewRequired:true}}:e)}>Undo room confirmation</button>
 <details className="secondary-details"><summary>Alignment & elevation controls</summary><p className="muted">Use two corresponding points from the original sheet frame and your shared project coordinate system. Reapplying alignment always starts from the original coordinates. Check a third known point independently before accepting engineering accuracy.</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{['Sheet A X','Sheet A Y','Sheet B X','Sheet B Y','Project A X (m)','Project A Y (m)','Project B X (m)','Project B Y (m)'].map((label,i)=><label key={label}>{label}<input type="number" step="any" value={coordinates[i]} onChange={e=>setCoordinates(old=>old.map((v,j)=>i===j?e.target.value:v))}/></label>)}<label>Floor identifier<input value={floor} onChange={e=>setFloor(e.target.value)} placeholder="L2"/></label><label>Measured elevation (m)<input type="number" step="any" value={elevation} onChange={e=>setElevation(e.target.value)}/></label></div><button onClick={()=>void align()}>Apply sheet alignment</button><button onClick={()=>void save(e=>key(e)===sheet?restoreSheetCoordinates(e):e)}>Restore original sheet coordinates</button></details></>}
 <p role="status">{message}</p></div></details>;
}