import Link from 'next/link';
import {assets} from '@/lib/data';
import {assetReadiness,projectReadiness} from '@/lib/twin-intelligence';

export default function HandoverPage(){
 const project=projectReadiness();
 return <>
  <div className="page-head"><div><div className="eyebrow">STRATUM Trust · Continuous Digital Handover</div><h1 className="title">Turnover readiness you can explain.</h1><p className="subtitle">Every percentage is calculated from persistent asset identity, engineering attributes, installation, inspection, testing, commissioning, warranty and Digital Immutable Record requirements. Select an asset to see exactly what is complete and what is blocking turnover.</p></div><div className="badge">LIVE RULES · V1</div></div>
  <div className="grid kpis"><div className="card"><div className="label">Tracked assets</div><div className="metric">{project.trackedAssets}</div></div><div className="card"><div className="label">Commissioned</div><div className="metric">{project.commissioned}/{project.trackedAssets}</div></div><div className="card"><div className="label">DIR verified</div><div className="metric">{project.dirVerified}/{project.trackedAssets}</div></div><div className="card"><div className="label">Turnover readiness</div><div className="metric">{project.score}%</div><div className="muted">{project.blockedAssets} asset{project.blockedAssets===1?'':'s'} blocked</div></div></div>
  <div className="card table-card" style={{marginTop:16}}><div className="section-head"><div><div className="eyebrow">Explainable readiness</div><h2>Asset turnover matrix</h2></div><span className="proof">DETERMINISTIC</span></div><table className="table"><thead><tr><th>Asset</th><th>Turnover</th><th>Commissioning</th><th>DIR</th><th>Blocking requirement</th><th>Passport</th></tr></thead><tbody>{assetReadiness.map(row=>{const asset=assets.find(a=>a.id===row.assetId)!;return <tr key={row.assetId}><td><strong>{row.assetName}</strong><div className="muted">{row.assetId} · {asset.location}</div></td><td><span className={row.score===100?'proof':'pending'}>{row.score}%</span></td><td>{row.commissioningScore}%</td><td>{asset.block?<span className="proof">Verified</span>:<span className="pending">Pending</span>}</td><td>{row.blockers.length?<span>{row.blockers.join(' · ')}</span>:<span className="proof">Ready</span>}</td><td><Link className="ghost" href={`/assets/${row.assetId}`}>Open</Link></td></tr>})}</tbody></table></div>
  <div className="grid two" style={{marginTop:16}}><div className="card"><div className="eyebrow">Commissioning gate</div><h2>Readiness is evidence-bound</h2><p className="subtitle">An asset cannot be declared ready while a critical installation, inspection, testing, commissioning or DIR requirement remains incomplete. AI explanations use the same controlled rules exposed through the Twin Agent API.</p><div className="button-row"><Link className="action" href="/workflows">Resolve blockers</Link><Link className="ghost" href="/evidence">Open evidence vault</Link></div></div><div className="card"><div className="eyebrow">Verified Asset Lineage</div><h2>One persistent asset</h2><div className="custody"><div><i/>Design<span>Source and engineering intent</span></div><div><i/>Build<span>Procurement, installation and evidence</span></div><div><i/>Commission<span>Tests, approvals and readiness</span></div><div><i/>Operate<span>Health, maintenance and replacement</span></div><div><i/>Trust<span>Approved events finalized as DIR</span></div></div></div></div>
 </>;
}
