const scenarios=[
 {name:'TX-01 failure',source:'Transformer TX-01',affected:'47 circuits · 3 critical systems',risk:'HIGH',action:'Transfer eligible loads, inspect redundant path and validate emergency sequence.'},
 {name:'MSB-01 isolation',source:'Main Switchboard MSB-01',affected:'2 floors · 19 downstream assets',risk:'CRITICAL',action:'Coordinate outage window and verify temporary power before isolation.'},
 {name:'+5 MW campus load',source:'AI Infrastructure Campus',affected:'Utility service · TX bank · primary distribution',risk:'MODERATE',action:'Run capacity review, feeder loading study and thermal margin validation.'}
];
export default function SimulationPage(){return <>
  <div className="page-head"><div><div className="eyebrow">STRATUM Simulate</div><h1 className="title">Ask what happens before it happens.</h1><p className="subtitle">Run controlled what-if scenarios against the project graph to understand upstream/downstream dependency, operational consequence and required mitigation before a failure, outage or capacity change occurs.</p></div><div className="badge">L7.5 SIMULATION</div></div>
  <div className="grid kpis"><div className="card"><div className="label">Scenario library</div><div className="metric">3</div></div><div className="card"><div className="label">Dependency edges</div><div className="metric">68</div></div><div className="card"><div className="label">Critical systems</div><div className="metric">5</div></div><div className="card"><div className="label">Simulation mode</div><div className="metric" style={{fontSize:22}}>Graph</div></div></div>
  <div className="grid two"><div className="card"><div className="eyebrow">Impact scenarios</div><div className="timeline">{scenarios.map(s=><div className="event" key={s.name}><i className="event-icon">↯</i><div><strong>{s.name}</strong><small>{s.source}<br/>{s.affected}<br/><span style={{color:'#d7e8f8'}}>{s.action}</span></small></div><span className={s.risk==='CRITICAL'?'pending':'status-chip'}>{s.risk}</span></div>)}</div></div>
  <div className="card"><div className="eyebrow">Dependency trace</div><h2>TX-01 → critical loads</h2><div className="custody"><div><i/>TX-01<span>Primary source</span></div><div><i/>MSB-01<span>Main distribution</span></div><div><i/>UPS-2A<span>Critical power continuity</span></div><div><i/>Panel CP-04<span>Critical branch</span></div><div><i/>Server Room 2<span>Business-critical load</span></div></div></div></div>
  <div className="card" style={{marginTop:16}}><div className="eyebrow">Simulation trust boundary</div><p className="subtitle">Simulations are decision-support models, not immutable facts. Only approved resulting actions, engineering decisions, field interventions and verified lifecycle outcomes can become Digital Immutable Records (DIR).</p></div>
</>}
