export type EngineeringReference={
 id:string;publisher:string;code:string;edition:string|null;title:string;category:string;
 publisherUrl:string;publishedReferenceVerifiedAsOf:string;
 applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION';
};

export const ENGINEERING_REFERENCE_REGISTRY:EngineeringReference[]=[
 {id:'nfpa-70-2026',publisher:'NFPA',code:'NFPA 70',edition:'2026',title:'National Electrical Code',category:'ELECTRICAL_CODE',publisherUrl:'https://www.nfpa.org/70',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-70e-2024',publisher:'NFPA',code:'NFPA 70E',edition:'2024',title:'Standard for Electrical Safety in the Workplace',category:'ELECTRICAL_SAFETY',publisherUrl:'https://www.nfpa.org/70e',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ashrae-90-1-2025',publisher:'ASHRAE/IES',code:'ASHRAE 90.1',edition:'2025',title:'Energy Standard for Sites and Buildings Except Low-Rise Residential Buildings',category:'BUILDING_ENERGY',publisherUrl:'https://www.ashrae.org/technical-resources/standards-and-guidelines/read-only-versions-of-ashrae-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ashrae-62-1-2025',publisher:'ASHRAE',code:'ASHRAE 62.1',edition:'2025',title:'Ventilation and Acceptable Indoor Air Quality',category:'VENTILATION_IAQ',publisherUrl:'https://www.ashrae.org/technical-resources/standards-and-guidelines/titles-purposes-and-scopes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ashrae-15-2024',publisher:'ASHRAE',code:'ASHRAE 15',edition:'2024',title:'Safety Standard for Refrigeration Systems',category:'REFRIGERATION_SAFETY',publisherUrl:'https://www.ashrae.org/technical-resources/bookstore/ashrae-refrigeration-resources',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'iso-16739-1-2024',publisher:'ISO',code:'ISO 16739-1',edition:'2024',title:'Industry Foundation Classes (IFC) for data sharing — Part 1: Data schema',category:'BIM_INTEROPERABILITY',publisherUrl:'https://www.iso.org/standard/84123.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'iso-55001-2024',publisher:'ISO',code:'ISO 55001',edition:'2024',title:'Asset management — Asset management system — Requirements',category:'ASSET_MANAGEMENT',publisherUrl:'https://www.iso.org/standard/83054.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'iso-27001-2022',publisher:'ISO/IEC',code:'ISO/IEC 27001',edition:'2022',title:'Information security management systems — Requirements',category:'INFORMATION_SECURITY',publisherUrl:'https://www.iso.org/standard/27001',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'iso-42001-2023',publisher:'ISO/IEC',code:'ISO/IEC 42001',edition:'2023',title:'Artificial intelligence — Management system',category:'AI_GOVERNANCE',publisherUrl:'https://www.iso.org/standard/42001',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-70b-2023',publisher:'NFPA',code:'NFPA 70B',edition:'2023',title:'Standard for Electrical Equipment Maintenance',category:'ELECTRICAL_MAINTENANCE',publisherUrl:'https://www.nfpa.org/electricalcycleofsafety',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-20-2025',publisher:'NFPA',code:'NFPA 20',edition:'2025',title:'Standard for the Installation of Stationary Pumps for Fire Protection',category:'FIRE_PROTECTION',publisherUrl:'https://link.nfpa.org/all-publications/20/2025',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-99-2024',publisher:'NFPA',code:'NFPA 99',edition:'2024',title:'Health Care Facilities Code',category:'HEALTHCARE_FACILITIES',publisherUrl:'https://www.nfpa.org/99',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-101-2024',publisher:'NFPA',code:'NFPA 101',edition:'2024',title:'Life Safety Code',category:'LIFE_SAFETY',publisherUrl:'https://www.nfpa.org/101',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nfpa-855-2026',publisher:'NFPA',code:'NFPA 855',edition:'2026',title:'Standard for the Installation of Stationary Energy Storage Systems',category:'ENERGY_STORAGE_FIRE_SAFETY',publisherUrl:'https://www.nfpa.org/855',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-1-2023',publisher:'NECA',code:'NECA 1',edition:'2023',title:'Standard for Good Workmanship in Electrical Construction',category:'ELECTRICAL_WORKMANSHIP',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-91-2023',publisher:'NECA',code:'NECA 91',edition:'2023',title:'Recommended Practice for Maintaining Electrical Equipment',category:'ELECTRICAL_MAINTENANCE',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-100-2024',publisher:'NECA',code:'NECA 100',edition:'2024',title:'Symbols for Electrical Construction Drawings',category:'ELECTRICAL_DOCUMENTATION',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-402-2020',publisher:'NECA',code:'NECA 402',edition:'2020',title:'Standard for Installing and Maintaining Motor Control Centers',category:'ELECTRICAL_EQUIPMENT_INSTALLATION',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-413-2024',publisher:'NECA',code:'NECA 413',edition:'2024',title:'Installing and Maintaining Electric Vehicle Supply Equipment',category:'EV_INFRASTRUCTURE',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-430-2025',publisher:'NECA',code:'NECA 430',edition:'2025',title:'Standard for Installing and Maintaining Medium-Voltage Switchgear',category:'MEDIUM_VOLTAGE_SWITCHGEAR',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'neca-714-2025',publisher:'NECA',code:'NECA 714',edition:'2025',title:'Recommended Practice for Firestopping Electrical Penetrations',category:'FIRESTOPPING',publisherUrl:'https://www.necanet.org/topics/codesandstandards/neis/the-standards',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'icc-ibc-2024',publisher:'ICC',code:'IBC',edition:'2024',title:'International Building Code',category:'BUILDING_CODE_MODEL',publisherUrl:'https://shop.iccsafe.org/2024-15-set-collection.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'icc-ifc-2024',publisher:'ICC',code:'IFC',edition:'2024',title:'International Fire Code',category:'FIRE_CODE_MODEL',publisherUrl:'https://shop.iccsafe.org/2024-15-set-collection.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'icc-iecc-2024',publisher:'ICC',code:'IECC',edition:'2024',title:'International Energy Conservation Code',category:'ENERGY_CODE_MODEL',publisherUrl:'https://shop.iccsafe.org/2024-15-set-collection.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'icc-imc-2024',publisher:'ICC',code:'IMC',edition:'2024',title:'International Mechanical Code',category:'MECHANICAL_CODE_MODEL',publisherUrl:'https://shop.iccsafe.org/2024-15-set-collection.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'icc-izc-2024',publisher:'ICC',code:'IZC',edition:'2024',title:'International Zoning Code',category:'ZONING_CODE_MODEL',publisherUrl:'https://shop.iccsafe.org/2024-15-set-collection.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part2-2025',publisher:'California Building Standards Commission',code:'CCR Title 24 Part 2',edition:'2025',title:'California Building Code',category:'CALIFORNIA_BUILDING_CODE',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part3-2025',publisher:'California Building Standards Commission',code:'CCR Title 24 Part 3',edition:'2025',title:'California Electrical Code',category:'CALIFORNIA_ELECTRICAL_CODE',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part4-2025',publisher:'California Building Standards Commission',code:'CCR Title 24 Part 4',edition:'2025',title:'California Mechanical Code',category:'CALIFORNIA_MECHANICAL_CODE',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part6-2025',publisher:'California Energy Commission / California Building Standards Commission',code:'CCR Title 24 Part 6',edition:'2025',title:'California Energy Code',category:'CALIFORNIA_ENERGY_CODE',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part9-2025',publisher:'California Building Standards Commission',code:'CCR Title 24 Part 9',edition:'2025',title:'California Fire Code',category:'CALIFORNIA_FIRE_CODE',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ca-title24-part11-2025',publisher:'California Building Standards Commission',code:'CCR Title 24 Part 11',edition:'2025',title:'California Green Building Standards Code (CALGreen)',category:'CALIFORNIA_GREEN_BUILDING',publisherUrl:'https://www.dgs.ca.gov/bsc/codes',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'asce-7-22',publisher:'ASCE/SEI',code:'ASCE/SEI 7',edition:'2022',title:'Minimum Design Loads and Associated Criteria for Buildings and Other Structures',category:'STRUCTURAL_LOADS',publisherUrl:'https://www.asce.org/publications-and-news/codes-and-standards/asce-sei-7-22',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'aisc-360-22',publisher:'AISC',code:'ANSI/AISC 360',edition:'2022',title:'Specification for Structural Steel Buildings',category:'STRUCTURAL_STEEL',publisherUrl:'https://www.aisc.org/aisc/publications/current-standards/aisc-360/',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'aisc-341-22',publisher:'AISC',code:'ANSI/AISC 341',edition:'2022',title:'Seismic Provisions for Structural Steel Buildings',category:'STRUCTURAL_STEEL_SEISMIC',publisherUrl:'https://www.aisc.org/aisc/publications/current-standards/',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ieee-1584-2018',publisher:'IEEE',code:'IEEE 1584',edition:'2018',title:'IEEE Guide for Performing Arc-Flash Hazard Calculations',category:'ARC_FLASH_ANALYSIS',publisherUrl:'https://standards.ieee.org/ieee/1584/5802/',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'iso-19650-1-2018',publisher:'ISO',code:'ISO 19650-1',edition:'2018',title:'Information management using building information modelling — Part 1: Concepts and principles',category:'BIM_INFORMATION_MANAGEMENT',publisherUrl:'https://www.iso.org/standard/68078.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ada-2010',publisher:'U.S. Department of Justice',code:'2010 ADA Standards',edition:'2010',title:'2010 ADA Standards for Accessible Design',category:'ACCESSIBILITY',publisherUrl:'https://www.ada.gov/law-and-regs/design-standards/2010-stds/',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'osha-1910-subpart-s',publisher:'OSHA',code:'29 CFR 1910 Subpart S',edition:null,title:'Electrical',category:'WORKPLACE_ELECTRICAL_SAFETY',publisherUrl:'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910SubpartS',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'nist-csf-2-0',publisher:'NIST',code:'NIST CSF 2.0',edition:'2.0',title:'Cybersecurity Framework',category:'CYBERSECURITY',publisherUrl:'https://www.nist.gov/cyberframework',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'hipaa-security-rule-current',publisher:'U.S. Department of Health and Human Services',code:'45 CFR Parts 160 and 164',edition:null,title:'HIPAA Security Rule',category:'HEALTH_INFORMATION_SECURITY',publisherUrl:'https://www.hhs.gov/hipaa/for-professionals/security/index.html',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'},
 {id:'ul-1008-current',publisher:'UL Solutions',code:'UL 1008',edition:null,title:'Transfer Switch Equipment',category:'TRANSFER_SWITCH_LISTING',publisherUrl:'https://www.ul.com/services/switch-certification-and-evaluation-services',publishedReferenceVerifiedAsOf:'2026-09-22',applicability:'REFERENCE_ONLY_UNTIL_PROJECT_AHJ_RESOLUTION'}
];

export function engineeringReference(id:string){return ENGINEERING_REFERENCE_REGISTRY.find(item=>item.id===id)||null}
