/** Discovery links, not licensed model assets or verified project equipment. */
export type OemSource={
 id:string;manufacturer:string;families:string[];componentKeys:string[];url:string;
 evidence:'CAD_BIM_PORTAL'|'PRODUCT_DOCUMENTS';
 formats:string[];fields:string[];access:string;
};
export const OEM_SOURCES:OemSource[]=[
 {id:'abb-electrification',manufacturer:'ABB',families:['MV/LV switchgear','distribution boards','dry-type transformers'],componentKeys:['utility-switchgear','lv-switchboard','dry-transformer'],url:'https://new.abb.com/low-voltage/building-information-modeling',evidence:'CAD_BIM_PORTAL',formats:['BIM','product documents'],fields:['rating','voltage','enclosure','dimensions','clearances'],access:'Use ABB Download Center or its listed BIM partners; check model-specific terms.'},
 {id:'abb-drives',manufacturer:'ABB',families:['AC drives','DC drives','motor control'],componentKeys:['vfd','motor-starter'],url:'https://new.abb.com/drives/tools-%28us%29/cad-drawings-%28us%29',evidence:'CAD_BIM_PORTAL',formats:['2D CAD','3D CAD'],fields:['drive rating','input/output voltage','enclosure','dimensions'],access:'Select the specific drive in ABB CAD Catalog; confirm export rights.'},
 {id:'hitachi-transformers',manufacturer:'Hitachi Energy',families:['distribution transformers','power transformers','dry-type transformers'],componentKeys:['utility-transformer','dry-transformer','oil-transformer'],url:'https://www.hitachienergy.com/products-and-solutions/transformers',evidence:'PRODUCT_DOCUMENTS',formats:['product data','technical documents'],fields:['kVA/MVA','voltage','losses','cooling','dimensions'],access:'Match serial/model and voltage class; obtain the project-specific outline drawing separately.'},
 {id:'ge-grid',manufacturer:'GE Vernova',families:['gas-insulated switchgear','utility distribution'],componentKeys:['utility-switchgear'],url:'https://www.gevernova.com/grid-solutions/hvmv_equipment/catalog/GIS.htm',evidence:'PRODUCT_DOCUMENTS',formats:['product brochures','technical documents'],fields:['voltage class','insulation','switching rating','dimensions'],access:'Confirm model and site configuration; some technical files require account access.'},
 {id:'schneider-bim',manufacturer:'Schneider Electric',families:['switchboards','transformers','panelboards','metering','safety switches'],componentKeys:['main-switchboard','dry-transformer','panelboard','metering-cabinet','disconnect'],url:'https://www.se.com/us/en/work/support/resources-and-tools/cad-drawings/',evidence:'CAD_BIM_PORTAL',formats:['Revit/BIM','CAD','product documents'],fields:['ratings','dimensions','mounting','clearances','manufacturer part number'],access:'Some models require sign-in or a configurable BIM tool; inspect each product license.'},
 {id:'siemens-cax',manufacturer:'Siemens',families:['switchgear','motor starters','drives','industrial controls'],componentKeys:['utility-switchgear','motor-starter','vfd','contactor'],url:'https://www.siemens.com/en-us/support/documentation-downloads/',evidence:'CAD_BIM_PORTAL',formats:['2D CAD','3D CAD','wiring diagrams','product data'],fields:['part number','ratings','voltage','dimensions','connection'],access:'CAx Download Manager is product-specific; confirm availability for the chosen SKU.'},
 {id:'eaton-bim',manufacturer:'Eaton',families:['MV switchgear','transformers','UPS','distribution'],componentKeys:['utility-switchgear','dry-transformer','ups','distribution-panel'],url:'https://www.eaton.com/us/en-us/support/business-resources/consultants-engineers/consultant---engineer-resources-for-medium-voltage-power---eaton/bim-models-and-drawings.html',evidence:'CAD_BIM_PORTAL',formats:['Revit/BIM','drawings','product documents'],fields:['voltage','rating','sections','dimensions','service clearances'],access:'Configure product-specific files in Eaton resources; check any plug-in and download conditions.'},
 {id:'legrand-bim',manufacturer:'Legrand',families:['busway','cable tray','raceway','network racks'],componentKeys:['busduct','cable-tray','wireway','data-cabinet'],url:'https://www.legrand.us/resources/bim-models',evidence:'CAD_BIM_PORTAL',formats:['BIM','product documents'],fields:['section','length','capacity','mounting','dimensions'],access:'Select the actual product and revision before importing BIM.'},
 {id:'legrand-devices',manufacturer:'Legrand',families:['receptacles','switches','floor boxes'],componentKeys:['duplex-receptacle','gfci','industrial-receptacle','junction-box'],url:'https://www.legrand.us/wiring-devices/outlets-and-receptacles/c/lgnd030600',evidence:'PRODUCT_DOCUMENTS',formats:['product specifications','SKU-level CAD where offered'],fields:['voltage','current','NEMA configuration','mounting','finish'],access:'Match the specific catalog number and drawing symbol before recording an outlet type.'},
 {id:'phoenix-terminal',manufacturer:'Phoenix Contact',families:['terminal blocks','control-panel interfaces'],componentKeys:['junction-box','contactor'],url:'https://www.phoenixcontact.com/en-ca/products/feed-through-terminal-block-us-25-rd-1748855',evidence:'CAD_BIM_PORTAL',formats:['3D CAD','circuit diagram','technical data'],fields:['part number','current','voltage','conductor size','dimensions'],access:'Example terminal-block SKU. Use the actual part record for product-specific 3D and data.'},
 {id:'nvent-enclosures',manufacturer:'nVent HOFFMAN',families:['electrical enclosures','cable management'],componentKeys:['junction-box','wireway'],url:'https://www.nvent.com/en-us/products/enclosures',evidence:'PRODUCT_DOCUMENTS',formats:['product data','CAD on selected SKUs'],fields:['dimensions','material','IP/NEMA','mounting','accessories'],access:'Specify enclosure series and SKU before retrieving CAD.'},
 {id:'rockwell-powerflex',manufacturer:'Rockwell Automation',families:['PowerFlex drives','motor controls'],componentKeys:['vfd','soft-starter','motor-starter'],url:'https://www.rockwellautomation.com/en-us/products/details.20GEG3D545LNDNNNNN.html',evidence:'PRODUCT_DOCUMENTS',formats:['DXF drawing','dimension drawing','product data'],fields:['catalog number','lifecycle status','rating','frame','dimensions'],access:'Example product record; search the actual catalog number for the matching documents.'},
 {id:'grundfos-pumps',manufacturer:'Grundfos',families:['commercial pumps','motor-driven pump systems'],componentKeys:['pump','motor'],url:'https://www.grundfos.com/solutions/learn/ecademy/all-courses/buildings-information-modeling/how-to-find-bim-assets-at-grundfos-product-center',evidence:'CAD_BIM_PORTAL',formats:['BIM','CAD','pump curves','product documents'],fields:['duty point','flow','head','power','dimensions','connections'],access:'Use Grundfos Product Center to generate a model and curve for the selected configuration.'},
 {id:'weg-motors',manufacturer:'WEG',families:['industrial motors','enclosed motor controls'],componentKeys:['motor','motor-starter'],url:'https://www.weg.net/catalog/weg/US/en/Spare-Parts/Motors/c/GLOBAL_SP_MOTORS/list',evidence:'CAD_BIM_PORTAL',formats:['2D CAD','3D CAD','product catalog'],fields:['frame','horsepower','voltage','efficiency','dimensions'],access:'Find exact motor product and frame in WEG catalog before downloading its CAD.'},
 {id:'trane-hvac',manufacturer:'Trane',families:['chillers','air handlers','rooftop units','cooling equipment'],componentKeys:[],url:'https://www.trane.com/commercial/north-america/us/en/support/resources/bim-and-selection-tools.html',evidence:'CAD_BIM_PORTAL',formats:['Revit/BIM','CAD','selection data'],fields:['electrical load','voltage','air/water capacity','dimensions','connections'],access:'Select an exact unit before using its electrical demand or geometry.'},
 {id:'vertiv-bim',manufacturer:'Vertiv',families:['UPS','power distribution','data center cooling'],componentKeys:['ups','data-cabinet'],url:'https://bim.vertiv.com/',evidence:'CAD_BIM_PORTAL',formats:['BIM','product documents'],fields:['power rating','voltage','cooling capacity','dimensions','service access'],access:'Confirm the exact product record and its download/reuse terms.'},
 {id:'notifier-docs',manufacturer:'NOTIFIER by Honeywell',families:['fire alarm control panels','detection systems'],componentKeys:['fire-alarm'],url:'https://buildings.honeywell.com/us/en/brands/our-brands/notifier/resources/document-center',evidence:'PRODUCT_DOCUMENTS',formats:['datasheets','installation manuals'],fields:['panel model','circuits','power demand','dimensions','battery requirements'],access:'Select panel model and regional approval; do not infer a fire-system installation from a generic library item.'},
 {id:'apc-rack-pdu',manufacturer:'APC by Schneider Electric',families:['rack PDUs','data center distribution'],componentKeys:['data-cabinet','distribution-panel'],url:'https://www.apc.com/shop/tradeups/us/en/products/Rack-PDU-Basic-Zero-U-5-7kW-120V-42-5-20/P-AP7562',evidence:'PRODUCT_DOCUMENTS',formats:['product specifications','CAD source on product record'],fields:['input','outlet count','load','mounting','rack units'],access:'Example rack PDU SKU; use the installed unit part number and current documents.'},
 {id:'cummins-power-suite',manufacturer:'Cummins',families:['generators','automatic transfer switches','paralleling controls'],componentKeys:['generator','ats'],url:'https://www.social.cummins.com/parts-and-service/digital-products-and-services/powersuite',evidence:'PRODUCT_DOCUMENTS',formats:['outline drawings','specification sheets','product data'],fields:['kW/kVA','voltage','fuel','dimensions','emissions','ATS rating'],access:'Select generator set/ATS configuration in Power Suite; drawings are not a browser-ready GLB.'},
 {id:'cat-power',manufacturer:'Caterpillar',families:['diesel generator sets','gas generator sets'],componentKeys:['generator'],url:'https://www.cat.com/en_US/products/new/power-systems/electric-power/diesel-generator-sets/1000029524.html',evidence:'PRODUCT_DOCUMENTS',formats:['product specifications','downloads'],fields:['kW','voltage','frequency','fuel','dimensions','emissions'],access:'Example C13 family page; bind the exact genset configuration and approved submittal.'},
 {id:'chargepoint-design',manufacturer:'ChargePoint',families:['commercial AC charging','DC fast charging'],componentKeys:['evse'],url:'https://www.chargepoint.com/solutions/specifications',evidence:'CAD_BIM_PORTAL',formats:['CAD','Revit','product specifications'],fields:['input load','output','connector','dimensions','mounting','network'],access:'Choose station format and regional specification; confirm download rights.'},
 {id:'tesla-charging',manufacturer:'Tesla',families:['Wall Connector','Supercharger'],componentKeys:['evse-tesla-supercharger-v3','evse'],url:'https://www.tesla.com/support/charging/product-guides',evidence:'PRODUCT_DOCUMENTS',formats:['installation guides','product data'],fields:['charger generation','power','connector','mounting','clearances'],access:'Product guides provide reference details; do not treat the community V3 GLB as Tesla OEM CAD.'},
 {id:'kempower-satellite',manufacturer:'Kempower',families:['Satellite charging dispensers','DC charging systems'],componentKeys:['evse-kempower-satellite-v2'],url:'https://kempower.com/solution/kempower-satellite/',evidence:'PRODUCT_DOCUMENTS',formats:['product specifications'],fields:['output','connector','cable','dimensions','power unit'],access:'Match generation, market and power-unit configuration before applying specs.'},
 {id:'alpitronic-hyc400',manufacturer:'Alpitronic',families:['HYC400 Series 2 DC charging'],componentKeys:['evse-alpitronic-hyc400-s2'],url:'https://www.alpitronic.it/en/hypercharger/hyc-400-series-2/',evidence:'PRODUCT_DOCUMENTS',formats:['datasheet','product configuration'],fields:['output','connectors','dimensions','cable length','power stack'],access:'Download the current datasheet for the selected market and configuration.'},
 {id:'delta-dc-wallbox',manufacturer:'Delta Electronics',families:['DC Wallbox 50 kW','commercial EV charging'],componentKeys:['evse-delta-dc-wallbox-50'],url:'https://www.delta-americas.com/en-US/products/EV-Charging/dcwallbox-50kW',evidence:'PRODUCT_DOCUMENTS',formats:['product specifications'],fields:['output','input','mounting','dimensions','cable'],access:'Verify the regional SKU and mounting variant before attaching data.'},
 {id:'abb-ev',manufacturer:'ABB E-mobility',families:['DC charging systems'],componentKeys:['evse'],url:'https://e-mobility.abb.com/',evidence:'PRODUCT_DOCUMENTS',formats:['product information'],fields:['output','connectors','input','dimensions'],access:'Confirm exact charger model and current regional documentation; a family page is not a CAD license.'},
 {id:'abb-terra-360',manufacturer:'ABB E-mobility',families:['Terra 360 DC charger'],componentKeys:['evse-abb-terra-360'],url:'https://global.abb/group/en/media/press-releases/abb-launches-the-worlds-fastest-electric-car-charger',evidence:'PRODUCT_DOCUMENTS',formats:['product announcement','published dimensions'],fields:['output','connectors','input','dimensions'],access:'Historical Terra 360 reference for the existing STRATUM reconstruction; obtain the current product submittal before project use.'},
 {id:'solaredge-docs',manufacturer:'SolarEdge',families:['PV inverters','optimizers','storage'],componentKeys:['solar-inverter','pv-array'],url:'https://knowledge-center.solaredge.com/us/search',evidence:'PRODUCT_DOCUMENTS',formats:['datasheets','installation guides'],fields:['DC input','AC output','voltage','efficiency','dimensions'],access:'Filter by model, region and document revision.'},
 {id:'enphase-docs',manufacturer:'Enphase',families:['microinverters','PV balance of system'],componentKeys:['solar-inverter','pv-array'],url:'https://enphase.com/installers/resources/documentation/microinverters',evidence:'PRODUCT_DOCUMENTS',formats:['datasheets','installation guides'],fields:['AC output','DC input','voltage','dimensions','compatibility'],access:'Match the exact IQ family, SKU and regional datasheet.'},
];
