/** SKU-level acquisition records. None of these is a licensed, imported viewer model. */
export type OemCadCandidate={
 id:string;sourceId:string;componentKey:string;manufacturer:string;sku:string;product:string;
 productUrl:string;cadUrl?:string;cadFormat:string;status:'SOURCE_IDENTIFIED'|'CAD_DOWNLOAD_IDENTIFIED'|'FILE_VERIFIED'|'GLB_APPROVED';
 dimensionsMeters?:[number,number,number];notes:string;
 modelUrl?:string;sourceSha256?:string;modelSha256?:string;
};

export const OEM_CAD_CANDIDATES:OemCadCandidate[]=[
 {id:'adafruit-bme280-2652',sourceId:'adafruit-bme280-cad',componentKey:'adafruit-bme280-2652',manufacturer:'Adafruit',sku:'2652',product:'BME280 temperature, humidity and pressure sensor breakout',productUrl:'https://www.adafruit.com/product/2652',cadUrl:'https://github.com/adafruit/Adafruit_CAD_Parts/blob/main/2652%20Adafruit%20BME280/Adafruit%20BME280.stl',cadFormat:'Manufacturer STL; converted to GLB',status:'GLB_APPROVED',dimensionsMeters:[.01778,.01905,.00297],modelUrl:'/models/oem/adafruit-bme280-2652.glb',sourceSha256:'c2f70a132cae7d11289bcb4fdb160f8e63b2ce12c7eb31945f1afb96b874aee7',modelSha256:'7e4aa411d95efcdece8f234debdde20fddf81e3d65f354621256a2c686a895d7',notes:'Exact manufacturer STL from Adafruit_CAD_Parts, MIT license. Board-only CAD converted to meter-space GLB; no project installed-state claim.'},
 {id:'phoenix-ut25-3044076',sourceId:'phoenix-terminal',componentKey:'terminal-block',manufacturer:'Phoenix Contact',sku:'3044076',product:'UT 2,5 feed-through terminal block',productUrl:'https://www.phoenixcontact.com/en-us/products/feed-through-terminal-block-ut-25-3044076',cadFormat:'3D CAD (download format to verify)',status:'SOURCE_IDENTIFIED',dimensionsMeters:[.0052,.0477,.0469],notes:'Official product record provides width 5.2 mm, height 47.7 mm and depth 46.9 mm. Download location, format, file hash, revision and redistribution terms still need verification.'},
 {id:'phoenix-mslkg5-0452014',sourceId:'phoenix-terminal',componentKey:'terminal-block',manufacturer:'Phoenix Contact',sku:'0452014',product:'MSLKG 5 protective conductor terminal block',productUrl:'https://www.phoenixcontact.com/en-us/products/ground-terminal-block-mslkg-5-0452014',cadFormat:'3D CAD (product page download)',status:'CAD_DOWNLOAD_IDENTIFIED',notes:'Official product result advertises 3D view and CAD download. Obtain the actual file and its permission terms before conversion or reuse.'},
 {id:'schneider-c10n32d100',sourceId:'schneider-bim',componentKey:'mccb',manufacturer:'Schneider Electric',sku:'C10N32D100',product:'ComPacT NSX100N 100 A three-pole circuit breaker',productUrl:'https://www.se.com/ph/en/product/C10N32D100/circuit-breaker-compact-nsx100n-50ka-at-415vac-micrologic-2-2-trip-unit-100a-3-poles-3d/',cadFormat:'STEP (regional CAD catalog; exact file to verify)',status:'SOURCE_IDENTIFIED',notes:'Exact regional SKU identified. Confirm the corresponding simplified 3D STEP download and mechanical dimensions before linking a model.'},
];
