import Link from 'next/link';
import AssetQR from '@/components/AssetQR';
import {assetLifecycle,liveAsset,publicEvidence} from '@/lib/server/live-views';
import {findAsset,evidence as demoEvidence} from '@/lib/data';
import {calculateAssetReadiness} from '@/lib/twin-intelligence';
export const dynamic='force-dynamic';
const date=(d:Date|string|null|undefined)=>d?new Date(d).toLocaleString('en-US',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const short=(s:string|null|undefined,n=18)=>s?s.length>n*2?`${s.slice(0,n)}…${s.slice(-n)}`:s:'—';

function demoToPassport(identifier:string){
 const d=findAsset(identifier);if(!d)return null;
 const p=(d.project||'').toString();
 return {
  id:d.id,asset_code:d.id,asset_type:d.type,name:d.name,model:d.model||null,serial_number:d.serial||null,location_label:d.location||null,status:d.status,qr_token:d.qrToken,specifications:d.specs||{},installed_at:d.installedAt||null,commissioned_at:d.commissionedAt||null,warranty_expires_at:d.warranty||null,project_code:p,project_name:p,site_name:d.site,system_name:d.system,manufacturer_name:d.manufacturer,latest_event_id:d.tx||null,latest_event_type:d.stages?.slice().reverse().find(s=>s.status==='verified')?.stage||'REGISTER_ASSET',latest_event_status:d.block?'VERIFIED':'PENDING',ledger_network:'stratum-devnet-1',ledger_tx_hash:d.tx||null,ledger_block_height:d.block||null,anchored_at:d.commissionedAt||d.installedAt||null,
  __demo:true,
  __stages:d.stages||[]
 } as any;
}

export default async function AssetDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const identifier=decodeURIComponent(id);
 let asset:any=null,events:any[]=[];let evidence:any[]=[];let backendOnline=true;
 try{asset=await liveAsset(identifier);if(asset){[events,evidence]=await Promise.all([assetLifecycle(asset.id),publicEvidence(asset.id)]);}}
 catch(error){backendOnline=false;console.error('Asset passport backend unavailable; using resilient passport fallback.',error);}
 if(!asset){asset=demoToPassport(identifier);if(asset){events=asset.__stages.map((s:any,i:number)=>({id:`demo-${i}`,event_type:s.stage,status:s.status==='verified'?'VERIFIED':s.status==='pending'?'SUBMITTED':'PLANNED',occurred_at:s.date||null,payload_sha256:null,evidence_package_sha256:null,performed_by_name:s.actor||null,approved_by_name:null,ledger_block_height:s.block||null}));evidence=demoEvidence.filter(e=>e.assetId===asset.id).map(e=>({id:e.id,kind:e.kind,sha256:e.hash,visibility:e.privacy,captured_at:null}));}}
 if(!asset)return <><div className="page-head"><div><div className="eyebrow">Asset Passport</div><h1 className="title">Asset not found</h1><p className="subtitle">This asset identifier does not exist in the current tenant or has not yet been registered.</p></div></div><div className="card"><div className="button-row"><Link className="action" href="/assets">Return to Asset Passports</Link><Link className="ghost" href="/twin">Open STRATUM Twin</Link></div></div></>;
 const qr=`https://stratumverifiedtwin.vercel.app/verify?q=${encodeURIComponent(asset.asset_code)}`;
 const readiness=asset.__demo?calculateAssetReadiness(findAsset(identifier)!):null;
 return <>
 {!backendOnline&&<div className="card" style={{marginBottom:16,borderColor:'#75592e'}}><div className="eyebrow">Passport available · live backend reconnecting</div><p className="subtitle" style={{marginTop:6}}>The passport remains accessible while the production data connection recovers. Live lifecycle and evidence records will replace fallback data automatically.</p></div>}
 <div className="page-head"><div><div className="eyebrow">Asset Passport · {asset.asset_code}</div><h1 className="title">{asset.name}</h1><p className="subtitle">{asset.manufacturer_name||'Manufacturer pending'} {asset.model||''} · Serial {asset.serial_number||'—'}</p></div><div className="button-row"><Link className="ghost" href={`/verify?q=${encodeURIComponent(asset.asset_code)}`}>Public verify</Link><Link className="action" href="/workflows">+ Lifecycle event</Link></div></div>
 <section className="grid asset-top"><div className="card"><div className="asset-identity"><div><span className="status-chip">{asset.status}</span><h2>{asset.system_name||'System unassigned'}</h2><p className="muted">{asset.project_name} · {asset.site_name} · {asset.location_label||'Location pending'}</p></div><div className="qr-wrap"><AssetQR value={qr} size={150}/><small>{asset.asset_code}</small></div></div><div className="spec-grid">{Object.entries(asset.specifications||{}).map(([k,v])=><div key={k}><span>{k}</span><strong>{typeof v==='string'?v:JSON.stringify(v)}</strong></div>)}<div><span>Installed</span><strong>{date(asset.installed_at)}</strong></div><div><span>Commissioned</span><strong>{date(asset.commissioned_at)}</strong></div><div><span>Warranty through</span><strong>{date(asset.warranty_expires_at)}</strong></div></div></div>
 <div className="card proof-panel"><div className="eyebrow">Latest Digital Immutable Record</div>{asset.ledger_block_height?<><div className="proof-seal">✓</div><h2>Verified in DIR</h2><div className="proof-data"><span>Record network</span><b>{asset.ledger_network||'stratum-devnet-1'}</b><span>Immutable record</span><b>#{asset.ledger_block_height}</b><span>Transaction reference</span><b className="mono" title={asset.ledger_tx_hash||''}>{short(asset.ledger_tx_hash)}</b><span>Lifecycle record</span><b className="mono">{short(asset.latest_event_id)}</b><span>Finalized</span><b>{date(asset.anchored_at)}</b></div></>:<><div className="proof-seal pending-seal">…</div><h2>Awaiting immutable lifecycle record</h2><p className="muted">Approved lifecycle evidence will appear here after DIR finalization.</p></>}</div></section>
 <section className="card lifecycle-card"><div className="section-head"><div><div className="eyebrow">Lifecycle</div><h2>Verified history</h2></div><span className="proof">{events.filter((e:any)=>e.status==='VERIFIED').length} verified</span></div><div className="vertical-timeline">{events.map((e:any)=><div className={`life-event ${e.status==='VERIFIED'?'verified':e.status==='SUBMITTED'?'pending':''}`} key={e.id}><i>{e.status==='VERIFIED'?'✓':e.status==='SUBMITTED'?'●':'○'}</i><div><strong>{e.event_type}</strong><span>{date(e.occurred_at)} · {e.performed_by_name||'Actor recorded'}{e.approved_by_name?` → approved by ${e.approved_by_name}`:''}</span><small className="mono">Payload {short(e.payload_sha256,14)} · Evidence {short(e.evidence_package_sha256,14)}</small></div><b>{e.ledger_block_height?`DIR ${e.ledger_block_height}`:e.status}</b></div>)}{!events.length&&<p className="muted">No lifecycle events recorded yet.</p>}</div></section>
 <section className="grid two"><div className="card"><div className="section-head"><div><div className="eyebrow">Evidence fingerprints</div><h3>Private files, verifiable integrity</h3></div></div>{evidence.length?evidence.map((d:any)=><div className="file-row" key={d.id}><div className="file-icon">SHA</div><div><strong>{d.kind}</strong><small>SHA-256 <span className="mono">{short(d.sha256,16)}</span> · {date(d.captured_at)}</small></div><span className="proof">{d.visibility}</span></div>):<p className="muted">No evidence linked yet.</p>}<p className="muted">Private file contents are not exposed by this passport; only verification metadata and cryptographic fingerprints are shown.</p></div><div className="card"><div className="eyebrow">Provenance</div><h3>Asset context</h3><div className="custody"><div><i/>Project<span>{asset.project_code} · {asset.project_name}</span></div><div><i/>Physical site<span>{asset.site_name}</span></div><div><i/>Electrical system<span>{asset.system_name||'Unassigned'}</span></div><div><i/>Equipment identity<span>{asset.asset_code} · {asset.serial_number||'No serial'}</span></div><div><i/>DIR<span>{asset.ledger_block_height?`Finalized immutable record ${asset.ledger_block_height}`:'Awaiting first immutable record'}</span></div></div></div></section>
 {readiness&&<section className="card" style={{marginTop:16}}><div className="section-head"><div><div className="eyebrow">Continuous digital handover</div><h2>{readiness.score}% turnover ready · {readiness.commissioningScore}% commissioning ready</h2></div><span className={readiness.ready?'proof':'pending'}>{readiness.ready?'READY':'BLOCKED'}</span></div><div className="spec-grid">{readiness.items.map(item=><div key={item.key}><span>{item.complete?'✓':'○'} {item.label}</span><strong>{item.complete?'Complete':item.critical?'Required blocker':'Outstanding'}</strong></div>)}</div></section>}
 </>;
}
